/* ********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *  \file     Bcm_Cfg.h
 *  \brief    BCM ECU Master Configuration Header
 *  \details  Generated by Vector DaVinci Developer 4.7.0 (simulated reference output)
 *            Combines signal IDs, PDU IDs, and application constants for BCM.
 *
 *  \note     GENERATED CODE — DO NOT EDIT
 *  -------------------------------------------------------------------------------------------------------------------
 *  KEY DIFFERENCES vs arxmlgen:
 *    - Professional tools use ComConf_* / RteConf_* naming (ECUC symbolic names)
 *    - Professional tools generate separate Rte_Type.h for type definitions
 *    - Professional tools add module version info macros
 *    - Professional tools include ECUC parameter IDs for runtime access
 *  SIMILARITY to arxmlgen:
 *    - Same content: signal IDs, PDU IDs, application constants, enums
 *    - Same #define pattern with documented CAN ID mapping
 *    - Same logical grouping (BSW reserved 0-15, ECU-specific 16+)
 *  -------------------------------------------------------------------------------------------------------------------
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  Copyright (c) Vector Informatik GmbH (simulated reference)
 * ********************************************************************************************************************/

#ifndef BCM_CFG_H
#define BCM_CFG_H

/* ********************************************************************************************************************
 *  VERSION INFO (professional tools always include this)
 * ********************************************************************************************************************/
#define BCM_CFG_MAJOR_VERSION    1u
#define BCM_CFG_MINOR_VERSION    0u
#define BCM_CFG_PATCH_VERSION    0u

/* ********************************************************************************************************************
 *  RTE SIGNAL IDS
 *  -------------------------------------------------------------------------------------------------------------------
 *  0–15: BSW well-known (shared across ECUs, reserved by Com/Rte)
 *  16+:  ECU-specific application signals
 * ********************************************************************************************************************/

/* BSW well-known signals — same across all ECUs */
#define RTE_SIG_TORQUE_REQUEST          0u
#define RTE_SIG_STEERING_ANGLE          1u
#define RTE_SIG_VEHICLE_SPEED           2u
#define RTE_SIG_BRAKE_PRESSURE          3u
#define RTE_SIG_MOTOR_STATUS            4u
#define RTE_SIG_BATTERY_VOLTAGE         5u
#define RTE_SIG_MOTOR_TEMP              6u
#define RTE_SIG_ESTOP_ACTIVE            7u
#define RTE_SIG_HEARTBEAT               8u
#define RTE_SIG_MOTOR_CURRENT           9u

/* BCM-specific signals */
#define BCM_SIG_VEHICLE_SPEED           16u
#define BCM_SIG_VEHICLE_STATE           17u
#define BCM_SIG_BODY_CONTROL_CMD        18u
#define BCM_SIG_LIGHT_HEADLAMP          19u
#define BCM_SIG_LIGHT_TAIL              20u
#define BCM_SIG_INDICATOR_LEFT          21u
#define BCM_SIG_INDICATOR_RIGHT         22u
#define BCM_SIG_HAZARD_ACTIVE           23u
#define BCM_SIG_DOOR_LOCK_STATE         24u
#define BCM_SIG_ESTOP_ACTIVE            25u
#define BCM_SIG_COUNT                   26u

/* ********************************************************************************************************************
 *  COM TX PDU IDS
 *  -------------------------------------------------------------------------------------------------------------------
 *  Internal Com PDU IDs mapped to CAN message IDs (documented in comments)
 * ********************************************************************************************************************/
#define BCM_COM_TX_LIGHT_STATUS         0u    /* CAN 0x400 */
#define BCM_COM_TX_INDICATOR_STATE      1u    /* CAN 0x401 */
#define BCM_COM_TX_DOOR_LOCK            2u    /* CAN 0x402 */
#define BCM_COM_TX_PDU_COUNT            3u

/* ********************************************************************************************************************
 *  COM RX PDU IDS
 * ********************************************************************************************************************/
#define BCM_COM_RX_VEHICLE_STATE        0u    /* CAN 0x100 */
#define BCM_COM_RX_MOTOR_CURRENT        1u    /* CAN 0x301 */
#define BCM_COM_RX_BODY_CMD             2u    /* CAN 0x350 */
#define BCM_COM_RX_PDU_COUNT            3u

/* ********************************************************************************************************************
 *  COM SIGNAL COUNT
 * ********************************************************************************************************************/
#define BCM_COM_SIGNAL_COUNT            12u   /* 6 TX + 6 RX */

/* ********************************************************************************************************************
 *  APPLICATION CONSTANTS
 * ********************************************************************************************************************/

/* Vehicle state enumeration */
#define BCM_VSTATE_INIT                 0u
#define BCM_VSTATE_READY                1u
#define BCM_VSTATE_DRIVING              2u
#define BCM_VSTATE_DEGRADED             3u
#define BCM_VSTATE_ESTOP                4u
#define BCM_VSTATE_FAULT                5u

/* Indicator timing */
#define BCM_INDICATOR_FLASH_ON_MS       330u   /* ~1.5 Hz flash rate */
#define BCM_INDICATOR_FLASH_OFF_MS      330u

/* Door lock */
#define BCM_AUTO_LOCK_SPEED_KPH         10u    /* Auto-lock above this speed */

/* ********************************************************************************************************************
 *  RUNNABLE COUNT
 * ********************************************************************************************************************/
#define BCM_RUNNABLE_COUNT              8u

#endif /* BCM_CFG_H */

/* ********************************************************************************************************************
 *  END OF FILE: Bcm_Cfg.h
 * ********************************************************************************************************************/
