/* ********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *  \file     Com_Cfg.h
 *  \brief    AUTOSAR Com - Module Configuration Header
 *  \details  Generated by Vector DaVinci Developer 4.7.0 (simulated reference output)
 *            This file represents what a professional AUTOSAR configurator would produce
 *            for the BCM ECU. Used as a quality comparison target for arxmlgen.
 *
 *  \note     GENERATED CODE — DO NOT EDIT
 *  \note     Generator: DaVinci Configurator Pro (simulated), based on AUTOSAR_SWS_COM 4.5.0
 *  -------------------------------------------------------------------------------------------------------------------
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  Copyright (c) Vector Informatik GmbH (simulated reference)
 * ********************************************************************************************************************/

#ifndef COM_CFG_H
#define COM_CFG_H

/* ********************************************************************************************************************
 *  INCLUDES
 * ********************************************************************************************************************/
#include "ComStack_Types.h"
#include "Com_Types.h"

/* ********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS — Signal IDs
 * ********************************************************************************************************************/

/* --- TX Signals (Provided by BCM) --- */
#define ComConf_ComSignal_SGN_Light_Headlamp_BCM_TX           0u
#define ComConf_ComSignal_SGN_Light_Tail_BCM_TX               1u
#define ComConf_ComSignal_SGN_Indicator_Left_BCM_TX           2u
#define ComConf_ComSignal_SGN_Indicator_Right_BCM_TX          3u
#define ComConf_ComSignal_SGN_Hazard_Active_BCM_TX            4u
#define ComConf_ComSignal_SGN_Door_Lock_State_BCM_TX          5u

/* --- RX Signals (Required by BCM) --- */
#define ComConf_ComSignal_SGN_Vehicle_State_CVC_RX            6u
#define ComConf_ComSignal_SGN_Vehicle_Speed_CVC_RX            7u
#define ComConf_ComSignal_SGN_Body_Cmd_Byte0_CVC_RX           8u
#define ComConf_ComSignal_SGN_Body_Cmd_Byte1_CVC_RX           9u
#define ComConf_ComSignal_SGN_EStop_Active_CVC_RX             10u
#define ComConf_ComSignal_SGN_Motor_Current_FZC_RX            11u

#define COM_CFG_SIGNAL_COUNT                                  12u

/* ********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS — IPdu IDs
 * ********************************************************************************************************************/

/* --- TX IPdus --- */
#define ComConf_ComIPdu_BCM_LightStatus_TX                    0u    /* CAN ID 0x400 */
#define ComConf_ComIPdu_BCM_IndicatorState_TX                 1u    /* CAN ID 0x401 */
#define ComConf_ComIPdu_BCM_DoorLock_TX                       2u    /* CAN ID 0x402 */

/* --- RX IPdus --- */
#define ComConf_ComIPdu_CVC_VehicleState_RX                   0u    /* CAN ID 0x100 */
#define ComConf_ComIPdu_FZC_MotorCurrent_RX                   1u    /* CAN ID 0x301 */
#define ComConf_ComIPdu_CVC_BodyCmd_RX                        2u    /* CAN ID 0x350 */

#define COM_CFG_TX_PDU_COUNT                                  3u
#define COM_CFG_RX_PDU_COUNT                                  3u

/* ********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS — Signal Access Types
 * ********************************************************************************************************************/
#define COM_CFG_TX_SIGNAL_FILTER_ALWAYS                       0u
#define COM_CFG_TX_SIGNAL_FILTER_NEVER                        1u
#define COM_CFG_TX_SIGNAL_FILTER_NEW_IS_WITHIN                2u
#define COM_CFG_TX_SIGNAL_FILTER_NEW_IS_OUTSIDE               3u

/* ********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 * ********************************************************************************************************************/

/** \brief Com signal access configuration (professional tool uses typed accessors) */
typedef uint16 Com_SignalIdType;
typedef uint16 Com_IpduIdType;

/* ********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 * ********************************************************************************************************************/

#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_MemMap */

extern const Com_ConfigType Com_ConfigData;

#define COM_STOP_SEC_CONST_UNSPECIFIED

#endif /* COM_CFG_H */

/* ********************************************************************************************************************
 *  END OF FILE: Com_Cfg.h
 * ********************************************************************************************************************/
