/* ********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *  \file     Rte_Cfg.c
 *  \brief    AUTOSAR RTE - Runnable and Signal Configuration (BCM)
 *  \details  Generated by Vector DaVinci Developer 4.7.0 (simulated reference output)
 *
 *  \note     GENERATED CODE — DO NOT EDIT
 *  \note     Project: Taktflow  ECU: BCM
 *  -------------------------------------------------------------------------------------------------------------------
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  Copyright (c) Vector Informatik GmbH (simulated reference)
 * ********************************************************************************************************************/

#include "Rte.h"
#include "Rte_Cfg.h"
#include "Os.h"   /* Professional tools include OS for task mapping */

/* ********************************************************************************************************************
 *  FORWARD DECLARATIONS — Runnable Entry Points
 *  -------------------------------------------------------------------------------------------------------------------
 *  KEY DIFFERENCE vs arxmlgen:
 *    - Professional tools generate Rte_<Swc>.h with full typed accessor prototypes
 *    - Professional tools map runnables to OS tasks, not a flat priority table
 *    - Professional tools generate Rte_Main.c with SchM integration
 *  SIMILARITY to arxmlgen:
 *    - Same signal table pattern (ID + initial value)
 *    - Same runnable function pointer + period pattern
 *    - Same aggregate config struct
 * ********************************************************************************************************************/

extern void Can_MainFunction_Read(void);
extern void Com_MainFunction_Rx(void);
extern void Bcm_ComBridge_10ms(void);
extern void Swc_Lights_10ms(void);
extern void Swc_Indicators_10ms(void);
extern void Swc_DoorLock_100ms(void);
extern void Com_MainFunction_Tx(void);
extern void Can_MainFunction_BusOff(void);

/* ********************************************************************************************************************
 *  LOCAL DATA — RTE Signal Configuration
 *  -------------------------------------------------------------------------------------------------------------------
 *  Professional tools assign signal IDs via ECUC RteSignal containers.
 *  Signal IDs are NOT guaranteed to match arxmlgen's sorted-by-name scheme.
 * ********************************************************************************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED

static CONST(Rte_SignalConfigType, RTE_CONST) Rte_SignalConfig[] =
{
    /* --- BSW Well-Known Signals (0–15) --- */
    /* These IDs are reserved and shared across all ECUs */
    { /* [0]  */ 0u,  0u },   /* RTE_SIG_TORQUE_REQUEST       */
    { /* [1]  */ 1u,  0u },   /* RTE_SIG_STEERING_ANGLE       */
    { /* [2]  */ 2u,  0u },   /* RTE_SIG_VEHICLE_SPEED        */
    { /* [3]  */ 3u,  0u },   /* RTE_SIG_BRAKE_PRESSURE       */
    { /* [4]  */ 4u,  0u },   /* RTE_SIG_MOTOR_STATUS         */
    { /* [5]  */ 5u,  0u },   /* RTE_SIG_BATTERY_VOLTAGE      */
    { /* [6]  */ 6u,  0u },   /* RTE_SIG_MOTOR_TEMP           */
    { /* [7]  */ 7u,  0u },   /* RTE_SIG_ESTOP_ACTIVE         */
    { /* [8]  */ 8u,  0u },   /* RTE_SIG_HEARTBEAT            */
    { /* [9]  */ 9u,  0u },   /* RTE_SIG_MOTOR_CURRENT        */
    { /* [10] */ 10u, 0u },   /* reserved                     */
    { /* [11] */ 11u, 0u },   /* reserved                     */
    { /* [12] */ 12u, 0u },   /* reserved                     */
    { /* [13] */ 13u, 0u },   /* reserved                     */
    { /* [14] */ 14u, 0u },   /* reserved                     */
    { /* [15] */ 15u, 0u },   /* reserved                     */

    /* --- BCM-Specific Signals (16+) --- */
    { /* [16] */ 16u, 0u },   /* BCM_SIG_VEHICLE_SPEED        */
    { /* [17] */ 17u, 0u },   /* BCM_SIG_VEHICLE_STATE  (init: BCM_VSTATE_INIT = 0) */
    { /* [18] */ 18u, 0u },   /* BCM_SIG_BODY_CONTROL_CMD     */
    { /* [19] */ 19u, 0u },   /* BCM_SIG_LIGHT_HEADLAMP       */
    { /* [20] */ 20u, 0u },   /* BCM_SIG_LIGHT_TAIL           */
    { /* [21] */ 21u, 0u },   /* BCM_SIG_INDICATOR_LEFT       */
    { /* [22] */ 22u, 0u },   /* BCM_SIG_INDICATOR_RIGHT      */
    { /* [23] */ 23u, 0u },   /* BCM_SIG_HAZARD_ACTIVE        */
    { /* [24] */ 24u, 0u },   /* BCM_SIG_DOOR_LOCK_STATE      */
    { /* [25] */ 25u, 0u },   /* BCM_SIG_ESTOP_ACTIVE         */
};

/* ********************************************************************************************************************
 *  LOCAL DATA — Runnable Configuration
 *  -------------------------------------------------------------------------------------------------------------------
 *  KEY DIFFERENCE vs arxmlgen:
 *    - Professional tools map runnables to OsTask via RteEventToTaskMapping
 *    - Professional tools generate SchM_<Swc>.h for scheduling integration
 *    - Professional tools support mode-dependent activation
 *  SIMILARITY to arxmlgen:
 *    - Same function pointer + period + priority pattern
 *    - Same execution order semantics (priority controls intra-tick ordering)
 *    - Same WdgM supervised entity binding
 * ********************************************************************************************************************/

static CONST(Rte_RunnableConfigType, RTE_CONST) Rte_RunnableConfig[] =
{
    /*  func,                       periodMs, priority, seId   */
    { Can_MainFunction_Read,           10u,      8u,     0xFFu },  /* CAN driver RX polling       */
    { Com_MainFunction_Rx,             10u,      7u,     0xFFu },  /* Com signal unpacking         */
    { Bcm_ComBridge_10ms,              10u,      6u,     0xFFu },  /* RTE ↔ Com signal bridge      */
    { Swc_Lights_10ms,                 10u,      5u,     0u    },  /* SE0: Light control SWC       */
    { Swc_Indicators_10ms,             10u,      4u,     1u    },  /* SE1: Indicator control SWC   */
    { Swc_DoorLock_100ms,             100u,      3u,     2u    },  /* SE2: Door lock SWC           */
    { Com_MainFunction_Tx,             10u,      2u,     0xFFu },  /* Com signal packing + TX      */
    { Can_MainFunction_BusOff,         10u,      1u,     0xFFu },  /* CAN bus-off recovery         */
};

/* ********************************************************************************************************************
 *  GLOBAL DATA — Aggregate Configuration
 * ********************************************************************************************************************/

CONST(Rte_ConfigType, RTE_CONST) Rte_ConfigData =
{
    /* .signalConfig   = */ Rte_SignalConfig,
    /* .signalCount    = */ 26u,
    /* .runnableConfig = */ Rte_RunnableConfig,
    /* .runnableCount  = */ 8u,
};

#define RTE_STOP_SEC_CONST_UNSPECIFIED

/* ********************************************************************************************************************
 *  END OF FILE: Rte_Cfg.c
 * ********************************************************************************************************************/
