/**
 * @file    CanIf_Cfg_Fzc.c
 * @brief   CanIf configuration for FZC — CAN ID to PDU routing
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "CanIf.h"
#include "Fzc_Cfg.h"

/* ==================================================================
 * TX PDU Configuration Table
 * Maps CAN TX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_TxPduConfigType fzc_tx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc, hth */
    { 0x011u,  FZC_COM_TX_FZC_HEARTBEAT,  4u, 0u },
    { 0x200u,  FZC_COM_TX_STEERING_STATUS,  8u, 0u },
    { 0x201u,  FZC_COM_TX_BRAKE_STATUS,  8u, 0u },
    { 0x210u,  FZC_COM_TX_BRAKE_FAULT,  4u, 0u },
    { 0x211u,  FZC_COM_TX_MOTOR_CUTOFF_REQ,  4u, 0u },
    { 0x220u,  FZC_COM_TX_LIDAR_DISTANCE,  8u, 0u },
    { 0x500u,  FZC_COM_TX_DTC_BROADCAST,  8u, 0u },
    { 0x7E9u,  FZC_COM_TX_UDS_RESP_FZC,  8u, 0u },
};

#define FZC_CANIF_TX_PDU_COUNT  (sizeof(fzc_tx_pdu_config) / sizeof(fzc_tx_pdu_config[0]))

/* ==================================================================
 * RX PDU Configuration Table
 * Maps CAN RX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_RxPduConfigType fzc_rx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc, isExtended */
    { 0x001u,  FZC_COM_RX_ESTOP_BROADCAST,  4u, FALSE },
    { 0x010u,  FZC_COM_RX_CVC_HEARTBEAT,  4u, FALSE },
    { 0x012u,  FZC_COM_RX_RZC_HEARTBEAT,  4u, FALSE },
    { 0x013u,  FZC_COM_RX_SC_STATUS,  4u, FALSE },
    { 0x014u,  FZC_COM_RX_ICU_HEARTBEAT,  4u, FALSE },
    { 0x015u,  FZC_COM_RX_TCU_HEARTBEAT,  4u, FALSE },
    { 0x016u,  FZC_COM_RX_BCM_HEARTBEAT,  4u, FALSE },
    { 0x100u,  FZC_COM_RX_VEHICLE_STATE,  6u, FALSE },
    { 0x101u,  FZC_COM_RX_TORQUE_REQUEST,  8u, FALSE },
    { 0x102u,  FZC_COM_RX_STEER_COMMAND,  8u, FALSE },
    { 0x103u,  FZC_COM_RX_BRAKE_COMMAND,  8u, FALSE },
    { 0x300u,  FZC_COM_RX_MOTOR_STATUS,  8u, FALSE },
    { 0x301u,  FZC_COM_RX_MOTOR_CURRENT,  8u, FALSE },
    { 0x302u,  FZC_COM_RX_MOTOR_TEMPERATURE,  8u, FALSE },
    { 0x303u,  FZC_COM_RX_BATTERY_STATUS,  6u, FALSE },
    { 0x350u,  FZC_COM_RX_BODY_CONTROL_CMD,  4u, FALSE },
    { 0x400u,  FZC_COM_RX_LIGHT_STATUS,  4u, FALSE },
    { 0x401u,  FZC_COM_RX_INDICATOR_STATE,  4u, FALSE },
    { 0x402u,  FZC_COM_RX_DOOR_LOCK_STATUS,  2u, FALSE },
    { 0x500u,  FZC_COM_RX_DTC_BROADCAST,  8u, FALSE },
    { 0x600u,  FZC_COM_RX_FZC_VIRTUAL_SENSORS,  8u, FALSE },
    { 0x601u,  FZC_COM_RX_RZC_VIRTUAL_SENSORS,  8u, FALSE },
    { 0x644u,  FZC_COM_RX_UDS_RESP_TCU,  8u, FALSE },
    { 0x7DFu,  FZC_COM_RX_UDS_FUNC_REQUEST,  8u, FALSE },
    { 0x7E0u,  FZC_COM_RX_UDS_PHYS_REQ_CVC,  8u, FALSE },
    { 0x7E1u,  FZC_COM_RX_UDS_PHYS_REQ_FZC,  8u, FALSE },
    { 0x7E2u,  FZC_COM_RX_UDS_PHYS_REQ_RZC,  8u, FALSE },
    { 0x7E3u,  FZC_COM_RX_UDS_PHYS_REQ_TCU,  8u, FALSE },
    { 0x7E8u,  FZC_COM_RX_UDS_RESP_CVC,  8u, FALSE },
    { 0x7EAu,  FZC_COM_RX_UDS_RESP_RZC,  8u, FALSE },
};

#define FZC_CANIF_RX_PDU_COUNT  (sizeof(fzc_rx_pdu_config) / sizeof(fzc_rx_pdu_config[0]))

/* ==================================================================
 * Aggregate CanIf Configuration
 * ================================================================== */

const CanIf_ConfigType fzc_canif_config = {
    .txPduConfig = fzc_tx_pdu_config,
    .txPduCount  = (uint8)FZC_CANIF_TX_PDU_COUNT,
    .rxPduConfig = fzc_rx_pdu_config,
    .rxPduCount  = (uint8)FZC_CANIF_RX_PDU_COUNT,
    .e2eRxCheck  = NULL_PTR,
};
