/**
 * @file    E2E_Cfg_Fzc.c
 * @brief   E2E protection configuration for FZC
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "E2E.h"
#include "Fzc_Cfg.h"

/* ==================================================================
 * E2E PDU Protection Config Type
 *
 * Maps a PDU to its E2E parameters so the BSW can automatically
 * apply E2E_Protect on TX and E2E_Check on RX.
 * ================================================================== */

typedef struct {
    uint8 pdu_id;         /* Com PDU ID (TX or RX) */
    uint8 data_id;        /* E2E data ID (4-bit) */
    uint8 counter_bit;    /* Bit position of alive counter in PDU */
    uint8 crc_bit;        /* Bit position of CRC8 in PDU */
} E2E_PduProtectCfgType;

/* ==================================================================
 * TX E2E Protection Config — applied before CAN transmit
 * ================================================================== */

static const E2E_PduProtectCfgType fzc_e2e_tx_config[] = {
    /* pduId,                                      dataId,  counterBit, crcBit */
    { FZC_COM_TX_FZC_HEARTBEAT,  0x03u,  4u,  8u },   /* FZC_Heartbeat */
    { FZC_COM_TX_STEERING_STATUS,  0x09u,  4u,  8u },   /* Steering_Status */
    { FZC_COM_TX_BRAKE_STATUS,  0x0Au,  4u,  8u },   /* Brake_Status */
    { FZC_COM_TX_BRAKE_FAULT,  0x0Bu,  4u,  8u },   /* Brake_Fault */
    { FZC_COM_TX_MOTOR_CUTOFF_REQ,  0x0Cu,  4u,  8u },   /* Motor_Cutoff_Req */
    { FZC_COM_TX_LIDAR_DISTANCE,  0x0Du,  4u,  8u },   /* Lidar_Distance */
};

#define FZC_E2E_TX_PROTECT_COUNT  6u

/* ==================================================================
 * RX E2E Protection Config — checked on CAN reception
 * ================================================================== */

static const E2E_PduProtectCfgType fzc_e2e_rx_config[] = {
    /* pduId,                                      dataId,  counterBit, crcBit */
    { FZC_COM_RX_ESTOP_BROADCAST,  0x01u,  4u,  8u },   /* EStop_Broadcast */
    { FZC_COM_RX_CVC_HEARTBEAT,  0x02u,  4u,  8u },   /* CVC_Heartbeat */
    { FZC_COM_RX_RZC_HEARTBEAT,  0x04u,  4u,  8u },   /* RZC_Heartbeat */
    { FZC_COM_RX_ICU_HEARTBEAT,  0x10u,  4u,  8u },   /* ICU_Heartbeat */
    { FZC_COM_RX_TCU_HEARTBEAT,  0x11u,  4u,  8u },   /* TCU_Heartbeat */
    { FZC_COM_RX_BCM_HEARTBEAT,  0x12u,  4u,  8u },   /* BCM_Heartbeat */
    { FZC_COM_RX_VEHICLE_STATE,  0x05u,  4u,  8u },   /* Vehicle_State */
    { FZC_COM_RX_TORQUE_REQUEST,  0x06u,  4u,  8u },   /* Torque_Request */
    { FZC_COM_RX_STEER_COMMAND,  0x07u,  4u,  8u },   /* Steer_Command */
    { FZC_COM_RX_BRAKE_COMMAND,  0x08u,  4u,  8u },   /* Brake_Command */
    { FZC_COM_RX_MOTOR_STATUS,  0x0Eu,  4u,  8u },   /* Motor_Status */
    { FZC_COM_RX_MOTOR_CURRENT,  0x0Fu,  4u,  8u },   /* Motor_Current */
    { FZC_COM_RX_MOTOR_TEMPERATURE,  0x00u,  4u,  8u },   /* Motor_Temperature */
    { FZC_COM_RX_BATTERY_STATUS,  0x13u,  4u,  8u },   /* Battery_Status */
};

#define FZC_E2E_RX_PROTECT_COUNT  14u

/* ==================================================================
 * Aggregate E2E Configuration
 * ================================================================== */

typedef struct {
    const E2E_PduProtectCfgType *txConfig;
    uint8                        txCount;
    const E2E_PduProtectCfgType *rxConfig;
    uint8                        rxCount;
} E2E_ProtectConfigType;

const E2E_ProtectConfigType fzc_e2e_config = {
    .txConfig = fzc_e2e_tx_config,
    .txCount  = FZC_E2E_TX_PROTECT_COUNT,
    .rxConfig = fzc_e2e_rx_config,
    .rxCount  = FZC_E2E_RX_PROTECT_COUNT,
};
