/**
 * @file    Cvc_Cfg_Platform.h
 * @brief   CVC platform-specific constants — POSIX (SIL/Docker)
 * @date    2026-03-15
 *
 * @details Timing and threshold constants tuned for Docker SIL simulation.
 *          Selected via -I path ordering in Makefile.posix.
 *          Target version: firmware/cvc/cfg/platform_target/Cvc_Cfg_Platform.h
 *
 *          Uses #undef before #define because Cvc_Cfg.h (generated by arxmlgen)
 *          unconditionally defines these constants with target-board defaults.
 *          This file is included AFTER Cvc_Cfg.h via Cvc_App.h, so #undef is
 *          required to override the codegen values for POSIX/SIL.
 *
 * @standard AUTOSAR EcuC pre-compile parameter pattern
 * @copyright Taktflow Systems 2026
 */
#ifndef CVC_CFG_PLATFORM_H
#define CVC_CFG_PLATFORM_H

/* ---- Override codegen defaults for POSIX/SIL ---- */

/** @brief  INIT hold: 1000 × 10ms = 10s (Docker boot is slower) */
#undef  CVC_INIT_HOLD_CYCLES
#define CVC_INIT_HOLD_CYCLES           1000u

/** @brief  Post-INIT grace: 1000 × 10ms = 10s (Docker fault signal settling) */
#undef  CVC_POST_INIT_GRACE_CYCLES
#define CVC_POST_INIT_GRACE_CYCLES     1000u

/** @brief  E2E SM FZC window: 16 slots (max E2E_SM_MAX_WINDOW) — absorbs
 *          Docker CPU scheduling jitter at SIL_TIME_SCALE=10 */
#undef  CVC_E2E_SM_FZC_WINDOW
#define CVC_E2E_SM_FZC_WINDOW          16u

/** @brief  E2E SM FZC max errors: tolerate 14/16 missed — need 2+ OKs */
#undef  CVC_E2E_SM_FZC_MAX_ERR_VALID
#define CVC_E2E_SM_FZC_MAX_ERR_VALID   14u

/** @brief  E2E SM RZC window: 16 slots — same Docker jitter tolerance */
#undef  CVC_E2E_SM_RZC_WINDOW
#define CVC_E2E_SM_RZC_WINDOW          16u

/** @brief  E2E SM RZC max errors: tolerate 14/16 missed — need 2+ OKs */
#undef  CVC_E2E_SM_RZC_MAX_ERR_VALID
#define CVC_E2E_SM_RZC_MAX_ERR_VALID   14u

/** @brief  CVC heartbeat E2E DataID — must match VPS/FZC/RZC expectations.
 *          Codegen sets 0x04 (from ARXML), VPS used 0x02. CVC TX uses this
 *          for its own heartbeat CRC. Keep 0x04 — consistent with ARXML. */
/* NOTE: CVC_E2E_HEARTBEAT_DATA_ID left at codegen value (0x04).
 *       FZC uses 0x03, RZC uses 0x04 for their own TX heartbeats.
 *       CVC RX checks FZC with DataID 0x03, RZC with 0x04 — defined in
 *       Swc_CvcCom.c RxTable, not here. No override needed. */

/** @brief  Creep guard debounce: 200 × 10ms = 2s SIL.
 *          Motor RPM feedback via CAN has 100-200ms wall latency in CI. */
#undef  CVC_CREEP_DEBOUNCE_TICKS
#define CVC_CREEP_DEBOUNCE_TICKS       200u

#endif /* CVC_CFG_PLATFORM_H */
