/**
 * @file    stm32g4xx_it.c
 * @brief   STM32G4xx interrupt handlers (minimal — SysTick + FDCAN)
 * @note    Generated by CubeMX, trimmed to only what CVC needs.
 */
#include "stm32g4xx_hal.h"

/* Cortex-M4 core interrupt handlers */

void NMI_Handler(void)
{
}

void HardFault_Handler(void)
{
    for (;;) { }
}

void MemManage_Handler(void)
{
    for (;;) { }
}

void BusFault_Handler(void)
{
    for (;;) { }
}

void UsageFault_Handler(void)
{
    for (;;) { }
}

void SVC_Handler(void)
{
}

void DebugMon_Handler(void)
{
}

void PendSV_Handler(void)
{
}

void SysTick_Handler(void)
{
    HAL_IncTick();
}

/* FDCAN1 interrupt handlers — delegate to HAL */
extern void Can_MainFunction_Read(void);

void FDCAN1_IT0_IRQHandler(void)
{
    Can_MainFunction_Read();
}

void FDCAN1_IT1_IRQHandler(void)
{
    /* TX complete / error — not used currently */
}
