/**
 * @file    PduR_Cfg_Cvc.c
 * @brief   PduR configuration for CVC — CanIf ↔ Com routing
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "PduR.h"
#include "Cvc_Cfg.h"

/* ==================================================================
 * RX Routing Table — CanIf RX PDU → Com RX PDU
 * ================================================================== */

static const PduR_RoutingTableType cvc_pdur_routing[] = {
    /* RxPduId (CanIf),                            Destination,       UpperPduId (Com) */
    { CVC_COM_RX_FZC_HEARTBEAT,  PDUR_DEST_COM,  CVC_COM_RX_FZC_HEARTBEAT },   /* 0x011 FZC_Heartbeat */
    { CVC_COM_RX_RZC_HEARTBEAT,  PDUR_DEST_COM,  CVC_COM_RX_RZC_HEARTBEAT },   /* 0x012 RZC_Heartbeat */
    { CVC_COM_RX_SC_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_SC_STATUS },   /* 0x013 SC_Status */
    { CVC_COM_RX_ICU_HEARTBEAT,  PDUR_DEST_COM,  CVC_COM_RX_ICU_HEARTBEAT },   /* 0x014 ICU_Heartbeat */
    { CVC_COM_RX_TCU_HEARTBEAT,  PDUR_DEST_COM,  CVC_COM_RX_TCU_HEARTBEAT },   /* 0x015 TCU_Heartbeat */
    { CVC_COM_RX_BCM_HEARTBEAT,  PDUR_DEST_COM,  CVC_COM_RX_BCM_HEARTBEAT },   /* 0x016 BCM_Heartbeat */
    { CVC_COM_RX_STEERING_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_STEERING_STATUS },   /* 0x200 Steering_Status */
    { CVC_COM_RX_BRAKE_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_BRAKE_STATUS },   /* 0x201 Brake_Status */
    { CVC_COM_RX_BRAKE_FAULT,  PDUR_DEST_COM,  CVC_COM_RX_BRAKE_FAULT },   /* 0x210 Brake_Fault */
    { CVC_COM_RX_MOTOR_CUTOFF_REQ,  PDUR_DEST_COM,  CVC_COM_RX_MOTOR_CUTOFF_REQ },   /* 0x211 Motor_Cutoff_Req */
    { CVC_COM_RX_LIDAR_DISTANCE,  PDUR_DEST_COM,  CVC_COM_RX_LIDAR_DISTANCE },   /* 0x220 Lidar_Distance */
    { CVC_COM_RX_MOTOR_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_MOTOR_STATUS },   /* 0x300 Motor_Status */
    { CVC_COM_RX_MOTOR_CURRENT,  PDUR_DEST_COM,  CVC_COM_RX_MOTOR_CURRENT },   /* 0x301 Motor_Current */
    { CVC_COM_RX_MOTOR_TEMPERATURE,  PDUR_DEST_COM,  CVC_COM_RX_MOTOR_TEMPERATURE },   /* 0x302 Motor_Temperature */
    { CVC_COM_RX_BATTERY_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_BATTERY_STATUS },   /* 0x303 Battery_Status */
    { CVC_COM_RX_LIGHT_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_LIGHT_STATUS },   /* 0x400 Light_Status */
    { CVC_COM_RX_INDICATOR_STATE,  PDUR_DEST_COM,  CVC_COM_RX_INDICATOR_STATE },   /* 0x401 Indicator_State */
    { CVC_COM_RX_DOOR_LOCK_STATUS,  PDUR_DEST_COM,  CVC_COM_RX_DOOR_LOCK_STATUS },   /* 0x402 Door_Lock_Status */
    { CVC_COM_RX_XCP_REQ_CVC,  PDUR_DEST_XCP,  CVC_COM_RX_XCP_REQ_CVC },   /* 0x550 XCP_Req_CVC → XCP */
    { CVC_COM_RX_XCP_REQ_FZC,  PDUR_DEST_XCP,  CVC_COM_RX_XCP_REQ_FZC },   /* 0x552 XCP_Req_FZC → XCP */
    { CVC_COM_RX_XCP_RESP_FZC,  PDUR_DEST_COM,  CVC_COM_RX_XCP_RESP_FZC },   /* 0x553 XCP_Resp_FZC */
    { CVC_COM_RX_XCP_REQ_RZC,  PDUR_DEST_XCP,  CVC_COM_RX_XCP_REQ_RZC },   /* 0x554 XCP_Req_RZC → XCP */
    { CVC_COM_RX_XCP_RESP_RZC,  PDUR_DEST_COM,  CVC_COM_RX_XCP_RESP_RZC },   /* 0x555 XCP_Resp_RZC */
    { CVC_COM_RX_XCP_REQ_SC,  PDUR_DEST_XCP,  CVC_COM_RX_XCP_REQ_SC },   /* 0x556 XCP_Req_SC → XCP */
    { CVC_COM_RX_XCP_RESP_SC,  PDUR_DEST_COM,  CVC_COM_RX_XCP_RESP_SC },   /* 0x557 XCP_Resp_SC */
    { CVC_COM_RX_UDS_RESP_TCU,  PDUR_DEST_COM,  CVC_COM_RX_UDS_RESP_TCU },   /* 0x644 UDS_Resp_TCU */
    { CVC_COM_RX_UDS_FUNC_REQUEST,  PDUR_DEST_COM,  CVC_COM_RX_UDS_FUNC_REQUEST },   /* 0x7DF UDS_Func_Request */
    { CVC_COM_RX_UDS_PHYS_REQ_CVC,  PDUR_DEST_CANTP,  CVC_COM_RX_UDS_PHYS_REQ_CVC },   /* 0x7E0 UDS_Phys_Req_CVC → CanTp (UDS) */
    { CVC_COM_RX_UDS_PHYS_REQ_FZC,  PDUR_DEST_COM,  CVC_COM_RX_UDS_PHYS_REQ_FZC },   /* 0x7E1 UDS_Phys_Req_FZC */
    { CVC_COM_RX_UDS_PHYS_REQ_RZC,  PDUR_DEST_COM,  CVC_COM_RX_UDS_PHYS_REQ_RZC },   /* 0x7E2 UDS_Phys_Req_RZC */
    { CVC_COM_RX_UDS_PHYS_REQ_TCU,  PDUR_DEST_COM,  CVC_COM_RX_UDS_PHYS_REQ_TCU },   /* 0x7E3 UDS_Phys_Req_TCU */
    { CVC_COM_RX_UDS_RESP_FZC,  PDUR_DEST_COM,  CVC_COM_RX_UDS_RESP_FZC },   /* 0x7E9 UDS_Resp_FZC */
    { CVC_COM_RX_UDS_RESP_RZC,  PDUR_DEST_COM,  CVC_COM_RX_UDS_RESP_RZC },   /* 0x7EA UDS_Resp_RZC */
};

/* ==================================================================
 * Aggregate PduR Configuration
 * ================================================================== */

const PduR_ConfigType cvc_pdur_config = {
    .routingTable = cvc_pdur_routing,
    .routingCount = (uint8)(sizeof(cvc_pdur_routing) / sizeof(cvc_pdur_routing[0])),
};
