/**
 * @file    Swc_FZC.c
 * @brief   SWC implementation for Swc_FZC (FZC)
 *
 * Generated by arxmlgen v1.0.0 — EDIT THIS FILE
 * This is a skeleton. Add your application logic here.
 * Source: TaktflowSystem.arxml
 */
#include "Swc_FZC.h"
#include "Rte_Swc_FZC.h"

/* ====================================================================
 * Runnable Implementations
 * ==================================================================== */

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 14
 */
void Can_MainFunction_Read(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 13
 */
void Com_MainFunction_Rx(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 12
 */
void Swc_FzcCom_Receive(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 11
 */
void Swc_FzcSensorFeeder_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 10
 */
void Swc_Steering_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 9
 */
void Swc_Brake_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 8
 */
void Swc_Lidar_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 7
 */
void Swc_Heartbeat_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 6
 */
void Swc_FzcSafety_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 5
 */
void Swc_Buzzer_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 4
 */
void Swc_FzcCanMonitor_Check(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 3
 */
void Swc_FzcCom_TransmitSchedule(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 2
 */
void Com_MainFunction_Tx(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 1
 */
void Can_MainFunction_BusOff(void)
{
    /* TODO: Add periodic processing logic */
}

