/**
 * @file    Rte_Swc_FzcCom.h
 * @brief   Typed RTE wrappers for Swc_FzcCom (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_FZCCOM_H
#define RTE_SWC_FZCCOM_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_FzcCom
 *
 * Usage: #include "Rte_Swc_FzcCom.h" in Swc_FzcCom source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read ECU_Health (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_ECU_Health(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_ECU_HEALTH, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read VehicleState (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_VehicleState(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_VEHICLE_STATE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read FaultMask (uint16)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_FaultMask(uint16 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_FAULT_MASK, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16)tmp;
    }
    return status;
}

/**
 * @brief  Read FaultReason (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_FaultReason(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_FAULT_REASON, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read EStop_Source (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_EStop_Source(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_ESTOP_SOURCE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read BrakeForceCmd (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_BrakeForceCmd(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_BRAKE_FORCE_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_CRC8 (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_CRC8(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_SC_CRC_8, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SteerAngleCmd (uint16)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SteerAngleCmd(uint16 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_STEER_ANGLE_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16)tmp;
    }
    return status;
}

/**
 * @brief  Read RelayState (boolean)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_RelayState(boolean *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_RELAY_STATE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (boolean)tmp;
    }
    return status;
}

/**
 * @brief  Read EStop_Active (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_EStop_Active(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_ESTOP_ACTIVE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_FaultFlags (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_FaultFlags(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_SC_FAULT_FLAGS, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SteerRateLimit (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SteerRateLimit(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_STEER_RATE_LIMIT, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_Mode (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_Mode(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_SC_MODE, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read SC_AliveCounter (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SC_AliveCounter(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_SC_ALIVE_COUNTER, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Write E2E_DataID (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_E2E_DataID(uint8 value)
{
    return Rte_Write(FZC_SIG_E_2_E_DATA_ID, (uint32)value);
}

/**
 * @brief  Write FaultType (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_FaultType(uint8 value)
{
    return Rte_Write(FZC_SIG_FAULT_TYPE, (uint32)value);
}

/**
 * @brief  Write FaultStatus (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_FaultStatus(uint8 value)
{
    return Rte_Write(FZC_SIG_FAULT_STATUS, (uint32)value);
}

/**
 * @brief  Write BrakeMode (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeMode(uint8 value)
{
    return Rte_Write(FZC_SIG_BRAKE_MODE, (uint32)value);
}

/**
 * @brief  Write ServoCurrent_mA (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_ServoCurrent_mA(uint16 value)
{
    return Rte_Write(FZC_SIG_SERVO_CURRENT_M_A, (uint32)value);
}

/**
 * @brief  Write SignalStrength (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SignalStrength(uint16 value)
{
    return Rte_Write(FZC_SIG_SIGNAL_STRENGTH, (uint32)value);
}

/**
 * @brief  Write MeasuredBrake (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MeasuredBrake(uint8 value)
{
    return Rte_Write(FZC_SIG_MEASURED_BRAKE, (uint32)value);
}

/**
 * @brief  Write CommandedAngle (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_CommandedAngle(uint16 value)
{
    return Rte_Write(FZC_SIG_COMMANDED_ANGLE, (uint32)value);
}

/**
 * @brief  Write RequestType (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_RequestType(uint8 value)
{
    return Rte_Write(FZC_SIG_REQUEST_TYPE, (uint32)value);
}

/**
 * @brief  Write E2E_CRC8 (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_E2E_CRC8(uint8 value)
{
    return Rte_Write(FZC_SIG_E_2_E_CRC_8, (uint32)value);
}

/**
 * @brief  Write ActualAngle (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_ActualAngle(uint16 value)
{
    return Rte_Write(FZC_SIG_ACTUAL_ANGLE, (uint32)value);
}

/**
 * @brief  Write OperatingMode (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_OperatingMode(uint8 value)
{
    return Rte_Write(FZC_SIG_OPERATING_MODE, (uint32)value);
}

/**
 * @brief  Write SteerMode (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SteerMode(uint8 value)
{
    return Rte_Write(FZC_SIG_STEER_MODE, (uint32)value);
}

/**
 * @brief  Write ECU_ID (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_ECU_ID(uint8 value)
{
    return Rte_Write(FZC_SIG_ECU_ID, (uint32)value);
}

/**
 * @brief  Write E2E_AliveCounter (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_E2E_AliveCounter(uint8 value)
{
    return Rte_Write(FZC_SIG_E_2_E_ALIVE_COUNTER, (uint32)value);
}

/**
 * @brief  Write Reason (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Reason(uint8 value)
{
    return Rte_Write(FZC_SIG_REASON, (uint32)value);
}

/**
 * @brief  Write SteerFaultStatus (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SteerFaultStatus(uint8 value)
{
    return Rte_Write(FZC_SIG_STEER_FAULT_STATUS, (uint32)value);
}

/**
 * @brief  Write BrakeFaultStatus (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeFaultStatus(uint8 value)
{
    return Rte_Write(FZC_SIG_BRAKE_FAULT_STATUS, (uint32)value);
}

/**
 * @brief  Write BrakePosition (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakePosition(uint8 value)
{
    return Rte_Write(FZC_SIG_BRAKE_POSITION, (uint32)value);
}

/**
 * @brief  Write SensorStatus (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SensorStatus(uint8 value)
{
    return Rte_Write(FZC_SIG_SENSOR_STATUS, (uint32)value);
}

/**
 * @brief  Write ObstacleZone (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_ObstacleZone(uint8 value)
{
    return Rte_Write(FZC_SIG_OBSTACLE_ZONE, (uint32)value);
}

/**
 * @brief  Write Distance_cm (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_Distance_cm(uint16 value)
{
    return Rte_Write(FZC_SIG_DISTANCE_CM, (uint32)value);
}

/**
 * @brief  Write CommandedBrake (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_CommandedBrake(uint8 value)
{
    return Rte_Write(FZC_SIG_COMMANDED_BRAKE, (uint32)value);
}

/**
 * @brief  Write UDS_Data (uint32)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_UDS_Data(uint32 value)
{
    return Rte_Write(FZC_SIG_UDS_DATA, (uint32)value);
}

/**
 * @brief  Write BrakeCommandEcho (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeCommandEcho(uint8 value)
{
    return Rte_Write(FZC_SIG_BRAKE_COMMAND_ECHO, (uint32)value);
}

#endif /* RTE_SWC_FZCCOM_H */
