/**
 * @file    Rte_Swc_Brake.h
 * @brief   Typed RTE wrappers for Swc_Brake (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_BRAKE_H
#define RTE_SWC_BRAKE_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Brake
 *
 * Usage: #include "Rte_Swc_Brake.h" in Swc_Brake source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read BrakeForceCmd (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_BrakeForceCmd(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_BRAKE_FORCE_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Write BrakePosition (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakePosition(uint8_t value)
{
    return Rte_Write(FZC_SIG_BRAKE_POSITION, (uint32_t)value);
}

/**
 * @brief  Write CommandedBrake (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_CommandedBrake(uint8_t value)
{
    return Rte_Write(FZC_SIG_COMMANDED_BRAKE, (uint32_t)value);
}

/**
 * @brief  Write BrakeFaultStatus (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeFaultStatus(uint8_t value)
{
    return Rte_Write(FZC_SIG_BRAKE_FAULT_STATUS, (uint32_t)value);
}

/**
 * @brief  Write BrakeMode (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeMode(uint8_t value)
{
    return Rte_Write(FZC_SIG_BRAKE_MODE, (uint32_t)value);
}

/**
 * @brief  Write MeasuredBrake (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MeasuredBrake(uint8_t value)
{
    return Rte_Write(FZC_SIG_MEASURED_BRAKE, (uint32_t)value);
}

/**
 * @brief  Write BrakeCommandEcho (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_BrakeCommandEcho(uint8_t value)
{
    return Rte_Write(FZC_SIG_BRAKE_COMMAND_ECHO, (uint32_t)value);
}

#endif /* RTE_SWC_BRAKE_H */
