/**
 * @file    Rte_Swc_Steering.h
 * @brief   Typed RTE wrappers for Swc_Steering (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_STEERING_H
#define RTE_SWC_STEERING_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Steering
 *
 * Usage: #include "Rte_Swc_Steering.h" in Swc_Steering source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read SteerAngleCmd (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SteerAngleCmd(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_STEER_ANGLE_CMD, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

/**
 * @brief  Read SteerRateLimit (uint8_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_SteerRateLimit(uint8_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(FZC_SIG_STEER_RATE_LIMIT, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8_t)tmp;
    }
    return status;
}

/**
 * @brief  Write SteerMode (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SteerMode(uint8_t value)
{
    return Rte_Write(FZC_SIG_STEER_MODE, (uint32_t)value);
}

/**
 * @brief  Write SteerFaultStatus (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_SteerFaultStatus(uint8_t value)
{
    return Rte_Write(FZC_SIG_STEER_FAULT_STATUS, (uint32_t)value);
}

#endif /* RTE_SWC_STEERING_H */
