/**
 * @file    Rte_Swc_FzcSensorFeeder.h
 * @brief   Typed RTE wrappers for Swc_FzcSensorFeeder (FZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_FZCSENSORFEEDER_H
#define RTE_SWC_FZCSENSORFEEDER_H

#include "Rte.h"
#include "Fzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_FzcSensorFeeder
 *
 * Usage: #include "Rte_Swc_FzcSensorFeeder.h" in Swc_FzcSensorFeeder source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

#endif /* RTE_SWC_FZCSENSORFEEDER_H */
