/**
 * @file    CanIf_Cfg_Icu.c
 * @brief   CanIf configuration for ICU — CAN ID to PDU routing
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "CanIf.h"
#include "Icu_Cfg.h"

/* ==================================================================
 * TX PDU Configuration Table
 * Maps CAN TX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_TxPduCfgType icu_tx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc */
    { 0x014u,  ICU_COM_TX_ICU_HEARTBEAT,  4u },
};

#define ICU_CANIF_TX_PDU_COUNT  (sizeof(icu_tx_pdu_config) / sizeof(icu_tx_pdu_config[0]))

/* ==================================================================
 * RX PDU Configuration Table
 * Maps CAN RX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_RxPduCfgType icu_rx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc */
    { 0x001u,  ICU_COM_RX_ESTOP_BROADCAST,  4u },
    { 0x010u,  ICU_COM_RX_CVC_HEARTBEAT,  4u },
    { 0x011u,  ICU_COM_RX_FZC_HEARTBEAT,  4u },
    { 0x012u,  ICU_COM_RX_RZC_HEARTBEAT,  4u },
    { 0x013u,  ICU_COM_RX_SC_STATUS,  4u },
    { 0x015u,  ICU_COM_RX_TCU_HEARTBEAT,  4u },
    { 0x100u,  ICU_COM_RX_VEHICLE_STATE,  6u },
    { 0x101u,  ICU_COM_RX_TORQUE_REQUEST,  8u },
    { 0x102u,  ICU_COM_RX_STEER_COMMAND,  8u },
    { 0x103u,  ICU_COM_RX_BRAKE_COMMAND,  8u },
    { 0x200u,  ICU_COM_RX_STEERING_STATUS,  8u },
    { 0x201u,  ICU_COM_RX_BRAKE_STATUS,  8u },
    { 0x210u,  ICU_COM_RX_BRAKE_FAULT,  4u },
    { 0x211u,  ICU_COM_RX_MOTOR_CUTOFF_REQ,  4u },
    { 0x220u,  ICU_COM_RX_LIDAR_DISTANCE,  8u },
    { 0x300u,  ICU_COM_RX_MOTOR_STATUS,  8u },
    { 0x301u,  ICU_COM_RX_MOTOR_CURRENT,  8u },
    { 0x302u,  ICU_COM_RX_MOTOR_TEMPERATURE,  8u },
    { 0x303u,  ICU_COM_RX_BATTERY_STATUS,  6u },
    { 0x350u,  ICU_COM_RX_BODY_CONTROL_CMD,  4u },
    { 0x400u,  ICU_COM_RX_LIGHT_STATUS,  4u },
    { 0x401u,  ICU_COM_RX_INDICATOR_STATE,  4u },
    { 0x402u,  ICU_COM_RX_DOOR_LOCK_STATUS,  2u },
    { 0x500u,  ICU_COM_RX_DTC_BROADCAST,  8u },
    { 0x644u,  ICU_COM_RX_UDS_RESP_TCU,  8u },
    { 0x7DFu,  ICU_COM_RX_UDS_FUNC_REQUEST,  8u },
    { 0x7E0u,  ICU_COM_RX_UDS_PHYS_REQ_CVC,  8u },
    { 0x7E1u,  ICU_COM_RX_UDS_PHYS_REQ_FZC,  8u },
    { 0x7E2u,  ICU_COM_RX_UDS_PHYS_REQ_RZC,  8u },
    { 0x7E3u,  ICU_COM_RX_UDS_PHYS_REQ_TCU,  8u },
    { 0x7E8u,  ICU_COM_RX_UDS_RESP_CVC,  8u },
    { 0x7E9u,  ICU_COM_RX_UDS_RESP_FZC,  8u },
    { 0x7EAu,  ICU_COM_RX_UDS_RESP_RZC,  8u },
};

#define ICU_CANIF_RX_PDU_COUNT  (sizeof(icu_rx_pdu_config) / sizeof(icu_rx_pdu_config[0]))

/* ==================================================================
 * Aggregate CanIf Configuration
 * ================================================================== */

const CanIf_ConfigType icu_canif_config = {
    .txPduConfig = icu_tx_pdu_config,
    .txPduCount  = (uint8)ICU_CANIF_TX_PDU_COUNT,
    .rxPduConfig = icu_rx_pdu_config,
    .rxPduCount  = (uint8)ICU_CANIF_RX_PDU_COUNT,
};
