/**
 * @file    Rte_Swc_Dashboard.h
 * @brief   Typed RTE wrappers for Swc_Dashboard (ICU)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_DASHBOARD_H
#define RTE_SWC_DASHBOARD_H

#include "Rte.h"
#include "Icu_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Dashboard
 *
 * Usage: #include "Rte_Swc_Dashboard.h" in Swc_Dashboard source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read MotorSpeed_RPM (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_MotorSpeed_RPM(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(ICU_SIG_MOTOR_SPEED_RPM, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

#endif /* RTE_SWC_DASHBOARD_H */
