/**
 * @file    Cvc_App.h
 * @brief   CVC application-specific constants — hand-authored, NOT generated
 * @date    2026-03-11
 *
 * @details Application-level constants for the Central Vehicle Controller:
 *          compatibility aliases, DTC extras, vehicle state events, pedal
 *          configuration, heartbeat, E2E state machine, dashboard, fault
 *          latching, creep guard, and SWC-level signal aliases.
 *
 *          PDU IDs, ARXML signal IDs, DTC IDs, E2E data IDs, enums, and
 *          thresholds are in the generated Cvc_Cfg.h — do NOT duplicate here.
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 * @copyright Taktflow Systems 2026
 */
#ifndef CVC_APP_H
#define CVC_APP_H

/* Platform-specific constants (selected via -I path in Makefile) */
#include "Cvc_Cfg_Platform.h"

/* ====================================================================
 * Compatibility aliases — bridge old names used in main.c / SWCs
 * to ARXML-generated fully-qualified names
 * ==================================================================== */

/* TX PDU aliases (main.c uses short names) */
#define CVC_COM_TX_ESTOP          CVC_COM_TX_ESTOP_BROADCAST
#define CVC_COM_TX_HEARTBEAT      CVC_COM_TX_CVC_HEARTBEAT
#define CVC_COM_TX_TORQUE_REQ     CVC_COM_TX_TORQUE_REQUEST
#define CVC_COM_TX_STEER_CMD      CVC_COM_TX_STEER_COMMAND
#define CVC_COM_TX_BRAKE_CMD      CVC_COM_TX_BRAKE_COMMAND
#define CVC_COM_TX_BODY_CMD       CVC_COM_TX_BODY_CONTROL_CMD
#define CVC_COM_TX_DTC            CVC_COM_TX_DTC_BROADCAST
#define CVC_COM_TX_UDS_RSP        CVC_COM_TX_UDS_RESP_CVC

/* RX PDU aliases */
#define CVC_COM_RX_FZC_HB         CVC_COM_RX_FZC_HEARTBEAT
#define CVC_COM_RX_RZC_HB         CVC_COM_RX_RZC_HEARTBEAT
#define CVC_COM_RX_MOTOR_CUTOFF   CVC_COM_RX_MOTOR_CUTOFF_REQ
#define CVC_COM_RX_LIDAR          CVC_COM_RX_LIDAR_DISTANCE
#define CVC_COM_RX_SC_RELAY       CVC_COM_RX_SC_STATUS
#define CVC_COM_RX_STEER_STATUS   CVC_COM_RX_STEERING_STATUS
#define CVC_COM_RX_ESTOP_INJECT   CVC_COM_RX_UDS_FUNC_REQUEST  /* placeholder */

/* Com signal aliases for heartbeat alive counter polling */
#define CVC_COM_SIG_FZC_HB_ALIVE  CVC_COM_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER
#define CVC_COM_SIG_RZC_HB_ALIVE  CVC_COM_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER

/* Swc_CvcCom signal aliases */
#define CVC_SIG_FZC_COMM_STATUS    CVC_SIG_FZC_HEARTBEAT_FAULT_STATUS
#define CVC_SIG_RZC_COMM_STATUS    CVC_SIG_RZC_HEARTBEAT_FAULT_STATUS

/* Short signal aliases for Rte_Swc_CanMonitor.h (codegen naming mismatch) */
#define CVC_SIG_MOTOR_DIRECTION       CVC_SIG_MOTOR_STATUS_MOTOR_DIRECTION
#define CVC_SIG_ECU_HEALTH            CVC_SIG_SC_STATUS_ECU_HEALTH
#define CVC_SIG_MOTOR_ENABLE          CVC_SIG_MOTOR_STATUS_MOTOR_ENABLE
#define CVC_SIG_FAULT_TYPE            CVC_SIG_BRAKE_FAULT_FAULT_TYPE
#define CVC_SIG_FAULT_REASON          CVC_SIG_SC_STATUS_FAULT_REASON
#define CVC_SIG_WINDING_TEMP_1_C      CVC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C
#define CVC_SIG_SERVO_CURRENT_M_A     CVC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A
#define CVC_SIG_SIGNAL_STRENGTH       CVC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH
#define CVC_SIG_CURRENT_M_A           CVC_SIG_MOTOR_CURRENT_CURRENT_M_A
#define CVC_SIG_MEASURED_BRAKE        CVC_SIG_BRAKE_FAULT_MEASURED_BRAKE
#define CVC_SIG_COMMANDED_ANGLE       CVC_SIG_STEERING_STATUS_COMMANDED_ANGLE
#define CVC_SIG_REQUEST_TYPE          CVC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE
#define CVC_SIG_SC_CRC_8              CVC_SIG_SC_STATUS_SC_CRC_8
#define CVC_SIG_ACTUAL_ANGLE          CVC_SIG_STEERING_STATUS_ACTUAL_ANGLE
#define CVC_SIG_WINDING_TEMP_2_C      CVC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C
#define CVC_SIG_STEER_MODE            CVC_SIG_STEERING_STATUS_STEER_MODE
#define CVC_SIG_MOTOR_SPEED_RPM       CVC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM
#define CVC_SIG_RELAY_STATE           CVC_SIG_SC_STATUS_RELAY_STATE
#define CVC_SIG_BATTERY_STATUS        CVC_SIG_BATTERY_STATUS_BATTERY_STATUS
#define CVC_SIG_REASON                CVC_SIG_MOTOR_CUTOFF_REQ_REASON
#define CVC_SIG_DERATING_PERCENT      CVC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT
#define CVC_SIG_STEER_FAULT_STATUS    CVC_SIG_STEERING_STATUS_STEER_FAULT_STATUS
#define CVC_SIG_BRAKE_FAULT_STATUS    CVC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS
#define CVC_SIG_BRAKE_POSITION        CVC_SIG_BRAKE_STATUS_BRAKE_POSITION
#define CVC_SIG_OVERCURRENT_FLAG      CVC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG
#define CVC_SIG_MOTOR_FAULT_STATUS    CVC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS
#define CVC_SIG_BATTERY_VOLTAGE_M_V   CVC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V
#define CVC_SIG_SENSOR_STATUS         CVC_SIG_LIDAR_DISTANCE_SENSOR_STATUS
#define CVC_SIG_SC_FAULT_FLAGS        CVC_SIG_SC_STATUS_SC_FAULT_FLAGS
#define CVC_SIG_TORQUE_ECHO           CVC_SIG_MOTOR_STATUS_TORQUE_ECHO
#define CVC_SIG_OBSTACLE_ZONE         CVC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE
#define CVC_SIG_DISTANCE_CM           CVC_SIG_LIDAR_DISTANCE_DISTANCE_CM
#define CVC_SIG_ALIVE_COUNTER         CVC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER
#define CVC_SIG_COMMANDED_BRAKE       CVC_SIG_BRAKE_FAULT_COMMANDED_BRAKE
#define CVC_SIG_SC_ALIVE_COUNTER      CVC_SIG_SC_STATUS_SC_ALIVE_COUNTER
#define CVC_SIG_BRAKE_COMMAND_ECHO    CVC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO
#define CVC_SIG_CURRENT_DIRECTION     CVC_SIG_MOTOR_CURRENT_CURRENT_DIRECTION
#define CVC_SIG_SC_MODE               CVC_SIG_SC_STATUS_SC_MODE

/* Short TX signal aliases for Rte_Swc_CanMonitor.h write functions */
#define CVC_SIG_E_2_E_DATA_ID        CVC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID
#define CVC_SIG_VEHICLE_STATE         CVC_SIG_VEHICLE_STATE_VEHICLE_STATE
#define CVC_SIG_FAULT_MASK            CVC_SIG_VEHICLE_STATE_FAULT_MASK
#define CVC_SIG_FAULT_STATUS          CVC_SIG_CVC_HEARTBEAT_FAULT_STATUS
#define CVC_SIG_SPEED_LIMIT           CVC_SIG_VEHICLE_STATE_SPEED_LIMIT
#define CVC_SIG_TAIL_LIGHT_CMD        CVC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD
#define CVC_SIG_ESTOP_SOURCE          CVC_SIG_ESTOP_BROADCAST_ESTOP_SOURCE
#define CVC_SIG_BRAKE_MODE            CVC_SIG_BRAKE_COMMAND_BRAKE_MODE
#define CVC_SIG_TURN_SIGNAL_CMD       CVC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD
#define CVC_SIG_ECU_SOURCE            CVC_SIG_DTC_BROADCAST_ECU_SOURCE
#define CVC_SIG_DTC_NUMBER            CVC_SIG_DTC_BROADCAST_DTC_NUMBER
#define CVC_SIG_FREEZE_FRAME_1        CVC_SIG_DTC_BROADCAST_FREEZE_FRAME_1
#define CVC_SIG_PEDAL_POSITION_2      CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2
#define CVC_SIG_BRAKE_FORCE_CMD       CVC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD
#define CVC_SIG_E_2_E_CRC_8          CVC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8
#define CVC_SIG_TORQUE_REQUEST        CVC_SIG_TORQUE_REQUEST_TORQUE_REQUEST
#define CVC_SIG_HEADLIGHT_CMD         CVC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD
#define CVC_SIG_OPERATING_MODE        CVC_SIG_CVC_HEARTBEAT_OPERATING_MODE
#define CVC_SIG_HAZARD_CMD            CVC_SIG_BODY_CONTROL_CMD_HAZARD_CMD
#define CVC_SIG_STEER_ANGLE_CMD       CVC_SIG_STEER_COMMAND_STEER_ANGLE_CMD
#define CVC_SIG_ECU_ID                CVC_SIG_CVC_HEARTBEAT_ECU_ID
#define CVC_SIG_OCCURRENCE_COUNT      CVC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT
#define CVC_SIG_E_2_E_ALIVE_COUNTER   CVC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER
#define CVC_SIG_PEDAL_FAULT           CVC_SIG_TORQUE_REQUEST_PEDAL_FAULT
#define CVC_SIG_TORQUE_LIMIT          CVC_SIG_VEHICLE_STATE_TORQUE_LIMIT
#define CVC_SIG_PEDAL_POSITION_1      CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1
#define CVC_SIG_DOOR_LOCK_CMD         CVC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD
#define CVC_SIG_ESTOP_ACTIVE          CVC_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE
#define CVC_SIG_FREEZE_FRAME_0        CVC_SIG_DTC_BROADCAST_FREEZE_FRAME_0
#define CVC_SIG_DIRECTION             CVC_SIG_TORQUE_REQUEST_DIRECTION
#define CVC_SIG_STEER_RATE_LIMIT      CVC_SIG_STEER_COMMAND_STEER_RATE_LIMIT
#define CVC_SIG_DTC_STATUS            CVC_SIG_DTC_BROADCAST_DTC_STATUS
#define CVC_SIG_UDS_DATA              CVC_SIG_UDS_FUNC_REQUEST_UDS_DATA

/* DTC aliases and extras */
#define CVC_DTC_DISPLAY_COMM         19u
#define CVC_DTC_CREEP_FAULT          20u
#define CVC_DTC_PEDAL_SENSOR1_FAIL   21u
#define CVC_DTC_PEDAL_SENSOR2_FAIL   22u
#define CVC_DTC_CAN_FZC_TIMEOUT     CVC_DTC_COMM_FZC_TIMEOUT
#define CVC_DTC_CAN_RZC_TIMEOUT     CVC_DTC_COMM_RZC_TIMEOUT
#define CVC_DTC_SAFE_STOP_ENTRY      23u
#define CVC_DTC_BATT_UNDERVOLT      CVC_DTC_BATTERY_LOW
#define CVC_DTC_MOTOR_CUTOFF_RX      24u
#define CVC_DTC_BRAKE_FAULT_RX       25u
#define CVC_DTC_STEERING_FAULT_RX    26u
#define CVC_DTC_ESTOP_ACTIVATED     CVC_DTC_ESTOP_FAULT
#define CVC_DTC_NVM_CRC_FAIL        27u

/* Self-test */
#define CVC_SELF_TEST_PASS           1u
#define CVC_SELF_TEST_FAIL           0u

/* Vehicle state events */
#define CVC_EVT_SELF_TEST_PASS       0u
#define CVC_EVT_SELF_TEST_FAIL       1u
#define CVC_EVT_PEDAL_FAULT_SINGLE   2u
#define CVC_EVT_PEDAL_FAULT_DUAL     3u
#define CVC_EVT_CAN_TIMEOUT_SINGLE   4u
#define CVC_EVT_CAN_TIMEOUT_DUAL     5u
#define CVC_EVT_ESTOP                6u
#define CVC_EVT_SC_KILL              7u
#define CVC_EVT_FAULT_CLEARED        8u
#define CVC_EVT_CAN_RESTORED         9u
#define CVC_EVT_VEHICLE_STOPPED     10u
#define CVC_EVT_MOTOR_CUTOFF        11u
#define CVC_EVT_BRAKE_FAULT         12u
#define CVC_EVT_STEERING_FAULT      13u
#define CVC_EVT_BATTERY_WARN        14u
#define CVC_EVT_BATTERY_CRIT        15u
#define CVC_EVT_CREEP_FAULT         16u
#define CVC_EVT_COUNT               17u
#define CVC_STATE_INVALID          0xFFu

/* Pedal fault enum */
#define CVC_PEDAL_NO_FAULT         0u
#define CVC_PEDAL_PLAUSIBILITY     1u
#define CVC_PEDAL_STUCK            2u
#define CVC_PEDAL_SENSOR1_FAIL     3u
#define CVC_PEDAL_SENSOR2_FAIL     4u

/* Additional vehicle states */
#define CVC_STATE_LIMP             6u
#define CVC_STATE_SHUTDOWN         7u
#define CVC_STATE_COUNT            8u

/* Pedal configuration */
#define CVC_PEDAL_RAMP_LIMIT            5u
#define CVC_PEDAL_MAX_RUN            1000u
#define CVC_PEDAL_MAX_DEGRADED        750u
#define CVC_PEDAL_MAX_LIMP            300u
#define CVC_PEDAL_DEADZONE_PERCENT      5u
#define CVC_PEDAL_PLAUS_DEBOUNCE        2u
#define CVC_PEDAL_STUCK_CYCLES        100u
#define CVC_PEDAL_LATCH_CLEAR_CYCLES   50u

/* Heartbeat */
#define CVC_HB_TX_PERIOD_MS       50u
#define CVC_HB_ALIVE_MAX          15u
#define CVC_ECU_ID_CVC             0x01u
#define CVC_ECU_ID_FZC             0x02u
#define CVC_ECU_ID_RZC             0x03u

/* E2E SM */
#ifndef CVC_E2E_SM_FZC_MIN_OK_INIT
  #define CVC_E2E_SM_FZC_MIN_OK_INIT     2u
#endif
#ifndef CVC_E2E_SM_FZC_MIN_OK_INV
  #define CVC_E2E_SM_FZC_MIN_OK_INV      3u
#endif
#ifndef CVC_E2E_SM_RZC_MIN_OK_INIT
  #define CVC_E2E_SM_RZC_MIN_OK_INIT      3u
#endif
#ifndef CVC_E2E_SM_RZC_MIN_OK_INV
  #define CVC_E2E_SM_RZC_MIN_OK_INV       3u
#endif

/* Dashboard / Safe-Stop / Fault Latching */
#define CVC_DASH_REFRESH_MS             200u
#define CVC_SAFE_STOP_RECOVERY_CYCLES   200u
#define CVC_FAULT_UNLATCH_CYCLES        300u
/* CVC_SAFE_BRAKE_CMD defined locally in Swc_CvcCom.c */

#define CVC_LATCH_IDX_ESTOP             0u
#define CVC_LATCH_IDX_SC_KILL           1u
#define CVC_LATCH_IDX_MOTOR_CUTOFF      2u
#define CVC_LATCH_IDX_BRAKE             3u
#define CVC_LATCH_IDX_STEERING          4u
#define CVC_LATCH_IDX_PEDAL_DUAL        5u
#define CVC_LATCH_IDX_CAN_DUAL          6u
#define CVC_LATCH_IDX_BATTERY_CRIT      7u
#define CVC_LATCH_IDX_CREEP             8u
#define CVC_LATCH_COUNT                 9u

/* Creep guard */
#define CVC_CREEP_SPEED_THRESH      50u
#define CVC_CREEP_TORQUE_THRESH     50u

/* E2E data ID alias */
#define CVC_E2E_VEHSTATE_DATA_ID  CVC_E2E_VEHICLE_STATE_DATA_ID

/* SWC-level signal aliases (dev short names -> ARXML names) */
#define CVC_SIG_SC_RELAY_KILL     CVC_SIG_SC_STATUS_RELAY_STATE
#define CVC_SIG_MOTOR_CUTOFF      CVC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE
#define CVC_SIG_BRAKE_FAULT       CVC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS
#define CVC_SIG_STEERING_FAULT    CVC_SIG_STEERING_STATUS_STEER_FAULT_STATUS
#define CVC_SIG_MOTOR_FAULT_RZC   CVC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS
#define CVC_SIG_PEDAL_POSITION    CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1
#define CVC_SIG_MOTOR_SPEED       CVC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM
#define CVC_SIG_PEDAL_RAW_1       CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1
#define CVC_SIG_PEDAL_RAW_2       CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2
#define CVC_SIG_MOTOR_CURRENT     CVC_SIG_MOTOR_CURRENT_CURRENT_M_A

#endif /* CVC_APP_H */
