/**
 * @file    Rte_Swc_VehicleState.h
 * @brief   Typed RTE wrappers for Swc_VehicleState (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_VEHICLESTATE_H
#define RTE_SWC_VEHICLESTATE_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_VehicleState
 *
 * Usage: #include "Rte_Swc_VehicleState.h" in Swc_VehicleState source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write VehicleState (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_VehicleState(uint8_t value)
{
    return Rte_Write(CVC_SIG_VEHICLE_STATE, (uint32_t)value);
}

#endif /* RTE_SWC_VEHICLESTATE_H */
