/**
 * @file    Rte_Swc_Dashboard.h
 * @brief   Typed RTE wrappers for Swc_Dashboard (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_DASHBOARD_H
#define RTE_SWC_DASHBOARD_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Dashboard
 *
 * Usage: #include "Rte_Swc_Dashboard.h" in Swc_Dashboard source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read Motor_Status_MotorSpeed_RPM (uint16_t)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_Motor_Status_MotorSpeed_RPM(uint16_t *data)
{
    uint32_t tmp;
    Rte_StatusType status = Rte_Read(CVC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint16_t)tmp;
    }
    return status;
}

/**
 * @brief  Write RZC_Virtual_Sensors_MotorSpeed_RPM (uint16_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_RZC_Virtual_Sensors_MotorSpeed_RPM(uint16_t value)
{
    return Rte_Write(CVC_SIG_RZC_VIRTUAL_SENSORS_MOTOR_SPEED_RPM, (uint32_t)value);
}

#endif /* RTE_SWC_DASHBOARD_H */
