/**
 * @file    Rte_Swc_EStop.h
 * @brief   Typed RTE wrappers for Swc_EStop (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_ESTOP_H
#define RTE_SWC_ESTOP_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_EStop
 *
 * Usage: #include "Rte_Swc_EStop.h" in Swc_EStop source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Write EStop_Active (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Active(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_ACTIVE, (uint32_t)value);
}

/**
 * @brief  Write EStop_Source (uint8_t)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_EStop_Source(uint8_t value)
{
    return Rte_Write(CVC_SIG_ESTOP_SOURCE, (uint32_t)value);
}

#endif /* RTE_SWC_ESTOP_H */
