/**
 * @file    Rte_Swc_SelfTest.h
 * @brief   Typed RTE wrappers for Swc_SelfTest (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_SELFTEST_H
#define RTE_SWC_SELFTEST_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_SelfTest
 *
 * Usage: #include "Rte_Swc_SelfTest.h" in Swc_SelfTest source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

#endif /* RTE_SWC_SELFTEST_H */
