/**
 * @file    Rte_Swc_Watchdog.h
 * @brief   Typed RTE wrappers for Swc_Watchdog (CVC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_WATCHDOG_H
#define RTE_SWC_WATCHDOG_H

#include "Rte.h"
#include "Cvc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Watchdog
 *
 * Usage: #include "Rte_Swc_Watchdog.h" in Swc_Watchdog source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

#endif /* RTE_SWC_WATCHDOG_H */
