/**
 * @file    Swc_CVC.h
 * @brief   SWC header for Swc_CVC (CVC)
 *
 * Generated by arxmlgen v1.0.0 — EDIT THIS FILE
 * This is a skeleton. Add your application logic here.
 * Source: TaktflowSystem.arxml
 */
#ifndef SWC_CVC_H
#define SWC_CVC_H

/* ====================================================================
 * Runnable Function Declarations
 * ==================================================================== */

/**
 * @brief  Periodic runnable — 1ms cycle
 */
void Can_MainFunction_Read(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Com_MainFunction_Rx(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Swc_EStop_MainFunction(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Swc_Pedal_MainFunction(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Swc_VehicleState_MainFunction(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Swc_Heartbeat_MainFunction(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Swc_Dashboard_MainFunction(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Com_MainFunction_Tx(void);

/**
 * @brief  Periodic runnable — 10ms cycle
 */
void Can_MainFunction_BusOff(void);

#endif /* SWC_CVC_H */
