/**
 * @file    E2E_Cfg_Rzc.c
 * @brief   E2E protection configuration for RZC
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "E2E.h"
#include "Rzc_Cfg.h"

/* ==================================================================
 * E2E PDU Protection Config Type
 *
 * Maps a PDU to its E2E parameters so the BSW can automatically
 * apply E2E_Protect on TX and E2E_Check on RX.
 * ================================================================== */

typedef struct {
    uint8_t pdu_id;         /* Com PDU ID (TX or RX) */
    uint8_t data_id;        /* E2E data ID (4-bit) */
    uint8_t counter_bit;    /* Bit position of alive counter in PDU */
    uint8_t crc_bit;        /* Bit position of CRC8 in PDU */
} E2E_PduProtectCfgType;

/* ==================================================================
 * TX E2E Protection Config — applied before CAN transmit
 * ================================================================== */

static const E2E_PduProtectCfgType rzc_e2e_tx_config[] = {
    /* pduId,                                      dataId,  counterBit, crcBit */
    { RZC_COM_TX_RZC_HEARTBEAT,  0x21u,  4u,  8u },   /* RZC_Heartbeat */
    { RZC_COM_TX_MOTOR_STATUS,  0x22u,  4u,  8u },   /* Motor_Status */
    { RZC_COM_TX_MOTOR_CURRENT,  0x23u,  4u,  8u },   /* Motor_Current */
    { RZC_COM_TX_MOTOR_TEMPERATURE,  0x25u,  4u,  8u },   /* Motor_Temperature */
    { RZC_COM_TX_BATTERY_STATUS,  0x26u,  4u,  8u },   /* Battery_Status */
};

#define RZC_E2E_TX_PROTECT_COUNT  5u

/* ==================================================================
 * RX E2E Protection Config — checked on CAN reception
 * ================================================================== */

static const E2E_PduProtectCfgType rzc_e2e_rx_config[] = {
    /* pduId,                                      dataId,  counterBit, crcBit */
    { RZC_COM_RX_ESTOP_BROADCAST,  0x01u,  4u,  8u },   /* EStop_Broadcast */
    { RZC_COM_RX_CVC_HEARTBEAT,  0x04u,  4u,  8u },   /* CVC_Heartbeat */
    { RZC_COM_RX_FZC_HEARTBEAT,  0x11u,  4u,  8u },   /* FZC_Heartbeat */
    { RZC_COM_RX_ICU_HEARTBEAT,  0x31u,  4u,  8u },   /* ICU_Heartbeat */
    { RZC_COM_RX_TCU_HEARTBEAT,  0x41u,  4u,  8u },   /* TCU_Heartbeat */
    { RZC_COM_RX_VEHICLE_STATE,  0x02u,  4u,  8u },   /* Vehicle_State */
    { RZC_COM_RX_TORQUE_REQUEST,  0x24u,  4u,  8u },   /* Torque_Request */
    { RZC_COM_RX_STEER_COMMAND,  0x14u,  4u,  8u },   /* Steer_Command */
    { RZC_COM_RX_BRAKE_COMMAND,  0x15u,  4u,  8u },   /* Brake_Command */
    { RZC_COM_RX_STEERING_STATUS,  0x12u,  4u,  8u },   /* Steering_Status */
    { RZC_COM_RX_BRAKE_STATUS,  0x13u,  4u,  8u },   /* Brake_Status */
    { RZC_COM_RX_BRAKE_FAULT,  0x16u,  4u,  8u },   /* Brake_Fault */
    { RZC_COM_RX_MOTOR_CUTOFF_REQ,  0x17u,  4u,  8u },   /* Motor_Cutoff_Req */
    { RZC_COM_RX_LIDAR_DISTANCE,  0x18u,  4u,  8u },   /* Lidar_Distance */
};

#define RZC_E2E_RX_PROTECT_COUNT  14u

/* ==================================================================
 * Aggregate E2E Configuration
 * ================================================================== */

typedef struct {
    const E2E_PduProtectCfgType *txConfig;
    uint8_t                      txCount;
    const E2E_PduProtectCfgType *rxConfig;
    uint8_t                      rxCount;
} E2E_ConfigType;

const E2E_ConfigType rzc_e2e_config = {
    .txConfig = rzc_e2e_tx_config,
    .txCount  = RZC_E2E_TX_PROTECT_COUNT,
    .rxConfig = rzc_e2e_rx_config,
    .rxCount  = RZC_E2E_RX_PROTECT_COUNT,
};
