#!/usr/bin/env bash
# Auto-generated by tools/test_gen/gen_signal_tests.py -- DO NOT EDIT
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
TEST_DIR="${REPO_ROOT}/test/unit/bsw"
FW="${REPO_ROOT}/firmware"

# Include paths
INCLUDES="\
  -I${FW}/bsw/include \
  -I${FW}/bsw/services/Com/include \
  -I${FW}/bsw/services/E2E/include \
  -I${FW}/bsw/services/Dem/include \
  -I${FW}/bsw/services/Det/include \
  -I${FW}/bsw/services/Rte/include \
  -I${FW}/bsw/services/SchM/include \
  -I${FW}/ecu/cvc/include \
  -I${FW}/ecu/cvc/cfg/platform_posix \
  -I${FW}/lib/vendor/unity"

# Source files
SOURCES="\
  ${TEST_DIR}/test_Com_signals_generated.c \
  ${FW}/bsw/services/Com/src/Com.c \
  ${FW}/ecu/cvc/cfg/Com_Cfg_Cvc.c \
  ${FW}/lib/vendor/unity/unity.c"

# Stubs (E2E, Dem, Det, Rte, SchM, PduR) — link with test stubs
STUBS="${TEST_DIR}/stubs_bsw.c"

echo "=== Compiling test_Com_signals_generated ==="
gcc -std=c11 -Wall -Wextra -Werror \
    -DUNIT_TEST \
    ${INCLUDES} \
    ${SOURCES} ${STUBS} \
    -o ${TEST_DIR}/test_Com_signals_generated

echo "=== Running tests ==="
${TEST_DIR}/test_Com_signals_generated
echo "=== All tests passed ==="
