#!/usr/bin/env python3
"""
A2L Generator — produces ASAM MCD-2MC A2L file from ELF symbols.

Scans the firmware ELF for exported measurement/calibration variables
and generates an A2L file that pyXCP can use for named access.

Usage:
    python tools/xcp/gen_a2l.py firmware.elf --ecu CVC --output cvc.a2l

Variables are discovered by naming convention:
  - g_dbg_*          → MEASUREMENT (debug counters)
  - com_tx_send_*    → MEASUREMENT (Com TX counters)
  - com_rx_*         → MEASUREMENT (Com RX state)
  - Swc_*            → MEASUREMENT (SWC state)
  - *_Cfg*           → CHARACTERISTIC (calibration — read-only for now)

Requires: arm-none-eabi-nm (for bare-metal ELF) or nm (for POSIX ELF)

@traces_to Phase 4: XCP measurement and calibration
"""

import argparse
import re
import subprocess
import sys
from datetime import datetime

# Variable patterns to include in A2L
MEASUREMENT_PATTERNS = [
    (re.compile(r'^g_dbg_'), 'Debug counter'),
    (re.compile(r'^com_tx_send_count'), 'Com TX send count'),
    (re.compile(r'^com_rx_pdu_quality'), 'Com RX PDU quality'),
    (re.compile(r'^g_dbg_com_'), 'Com debug counter'),
    (re.compile(r'^g_dbg_xcp_'), 'XCP debug counter'),
    (re.compile(r'^Hb_AliveCounter'), 'Heartbeat alive counter'),
    (re.compile(r'^Hb_CycleCounter'), 'Heartbeat cycle counter'),
    (re.compile(r'^Safety_Status'), 'Safety status'),
    (re.compile(r'^Brake_Position'), 'Brake position'),
    (re.compile(r'^Brake_Fault'), 'Brake fault code'),
    (re.compile(r'^Pedal_Position'), 'Pedal position'),
    (re.compile(r'^Pedal_Fault'), 'Pedal fault code'),
]

# Size → A2L data type mapping
SIZE_MAP = {
    1: ('UBYTE', 'UWORD', 0, 255),
    2: ('UWORD', 'UWORD', 0, 65535),
    4: ('ULONG', 'ULONG', 0, 4294967295),
}


def parse_nm_output(nm_output: str) -> list[dict]:
    """Parse `nm -S` output into symbol list."""
    symbols = []
    for line in nm_output.strip().split('\n'):
        parts = line.split()
        if len(parts) < 4:
            continue
        addr_str, size_str, sym_type, name = parts[0], parts[1], parts[2], parts[3]
        # Only include data symbols (B=BSS, D=Data, G=small data, R=rodata)
        if sym_type.upper() not in ('B', 'D', 'G', 'R', 'T'):
            continue
        # Skip code symbols for now
        if sym_type.upper() == 'T':
            continue
        try:
            addr = int(addr_str, 16)
            size = int(size_str, 16)
        except ValueError:
            continue
        symbols.append({'name': name, 'addr': addr, 'size': size, 'type': sym_type})
    return symbols


def match_measurement(name: str) -> str | None:
    """Check if symbol name matches a measurement pattern."""
    for pattern, description in MEASUREMENT_PATTERNS:
        if pattern.search(name):
            return description
    return None


def generate_a2l(symbols: list[dict], ecu_name: str) -> str:
    """Generate A2L file content from symbol list."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    measurements = []

    for sym in symbols:
        desc = match_measurement(sym['name'])
        if desc is None:
            continue
        size = sym['size']
        if size > 4 or size == 0:
            # Skip arrays and large structures (handle individually if needed)
            # For arrays, we could generate indexed measurements, but keep it simple
            if size <= 64:
                # Small array — generate as UBYTE array measurement
                measurements.append({
                    'name': sym['name'],
                    'addr': sym['addr'],
                    'size': 1,
                    'count': size,
                    'desc': desc,
                    'array': True,
                })
            continue
        if size not in SIZE_MAP:
            continue
        measurements.append({
            'name': sym['name'],
            'addr': sym['addr'],
            'size': size,
            'count': 1,
            'desc': desc,
            'array': False,
        })

    lines = []
    lines.append(f'/* A2L file generated by gen_a2l.py — {now} */')
    lines.append(f'/* ECU: {ecu_name} — {len(measurements)} measurements */')
    lines.append('')
    lines.append('ASAP2_VERSION 1 71')
    lines.append('')
    lines.append(f'/begin PROJECT {ecu_name}_XCP "Taktflow {ecu_name} XCP Project"')
    lines.append(f'  /begin MODULE {ecu_name} "Taktflow {ecu_name} ECU"')
    lines.append('')
    lines.append('    /begin MOD_PAR ""')
    lines.append(f'      EPK "{ecu_name} V1.0"')
    lines.append('    /end MOD_PAR')
    lines.append('')
    lines.append('    /begin MOD_COMMON ""')
    lines.append('      BYTE_ORDER MSB_LAST')  # Little-endian (STM32)
    lines.append('    /end MOD_COMMON')
    lines.append('')

    # COMPU_METHODs
    lines.append('    /begin COMPU_METHOD CM_IDENTICAL ""')
    lines.append('      IDENTICAL "%3.0" ""')
    lines.append('    /end COMPU_METHOD')
    lines.append('')

    # MEASUREMENT definitions
    for m in measurements:
        dt, dep, lo, hi = SIZE_MAP.get(m['size'], ('UBYTE', 'UWORD', 0, 255))
        lines.append(f'    /begin MEASUREMENT {m["name"]} "{m["desc"]}"')
        lines.append(f'      {dt} CM_IDENTICAL 0 0 {lo} {hi}')
        lines.append(f'      ECU_ADDRESS 0x{m["addr"]:08X}')
        if m.get('array') and m['count'] > 1:
            lines.append(f'      MATRIX_DIM {m["count"]}')
        lines.append(f'    /end MEASUREMENT')
        lines.append('')

    lines.append(f'  /end MODULE')
    lines.append(f'/end PROJECT')
    lines.append('')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate A2L from ELF')
    parser.add_argument('elf', help='Path to ELF file')
    parser.add_argument('--ecu', default='CVC', help='ECU name (default: CVC)')
    parser.add_argument('--output', '-o', default=None, help='Output A2L file')
    parser.add_argument('--nm', default='nm', help='nm tool path (default: nm)')
    args = parser.parse_args()

    # Run nm -S to get symbol sizes
    try:
        result = subprocess.run(
            [args.nm, '-S', '--defined-only', args.elf],
            capture_output=True, text=True, check=True
        )
    except FileNotFoundError:
        print(f"Error: '{args.nm}' not found. Install binutils or specify --nm path.", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        print(f"Error running nm: {e.stderr}", file=sys.stderr)
        return 1

    symbols = parse_nm_output(result.stdout)
    print(f"Parsed {len(symbols)} symbols from {args.elf}")

    # Filter to measurements
    matched = [s for s in symbols if match_measurement(s['name'])]
    print(f"Matched {len(matched)} measurement variables")

    a2l = generate_a2l(symbols, args.ecu.upper())

    output = args.output or f"{args.ecu.lower()}.a2l"
    with open(output, 'w') as f:
        f.write(a2l)
    print(f"Written: {output}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
