/**
 * @file    Tcu_Cfg.h
 * @brief   TCU configuration — all TCU-specific ID definitions
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef TCU_CFG_H
#define TCU_CFG_H

/* ====================================================================
 * RTE Signal IDs (offset 16 from BSW well-known)
 * ==================================================================== */

#define TCU_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    16u
#define TCU_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    17u
#define TCU_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    18u
#define TCU_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    19u
#define TCU_SIG_BCM_HEARTBEAT_ECU_ID    20u
#define TCU_SIG_BATTERY_STATUS_BATTERY_STATUS    21u
#define TCU_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V    22u
#define TCU_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER    23u
#define TCU_SIG_BATTERY_STATUS_E_2_E_CRC_8    24u
#define TCU_SIG_BATTERY_STATUS_E_2_E_DATA_ID    25u
#define TCU_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD    26u
#define TCU_SIG_BODY_CONTROL_CMD_HAZARD_CMD    27u
#define TCU_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD    28u
#define TCU_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD    29u
#define TCU_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD    30u
#define TCU_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    31u
#define TCU_SIG_BRAKE_COMMAND_BRAKE_MODE    32u
#define TCU_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    33u
#define TCU_SIG_BRAKE_COMMAND_E_2_E_CRC_8    34u
#define TCU_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    35u
#define TCU_SIG_BRAKE_COMMAND_VEHICLE_STATE    36u
#define TCU_SIG_BRAKE_FAULT_COMMANDED_BRAKE    37u
#define TCU_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    38u
#define TCU_SIG_BRAKE_FAULT_E_2_E_CRC_8    39u
#define TCU_SIG_BRAKE_FAULT_E_2_E_DATA_ID    40u
#define TCU_SIG_BRAKE_FAULT_FAULT_TYPE    41u
#define TCU_SIG_BRAKE_FAULT_MEASURED_BRAKE    42u
#define TCU_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    43u
#define TCU_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    44u
#define TCU_SIG_BRAKE_STATUS_BRAKE_MODE    45u
#define TCU_SIG_BRAKE_STATUS_BRAKE_POSITION    46u
#define TCU_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    47u
#define TCU_SIG_BRAKE_STATUS_E_2_E_CRC_8    48u
#define TCU_SIG_BRAKE_STATUS_E_2_E_DATA_ID    49u
#define TCU_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    50u
#define TCU_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    51u
#define TCU_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    52u
#define TCU_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    53u
#define TCU_SIG_CVC_HEARTBEAT_ECU_ID    54u
#define TCU_SIG_CVC_HEARTBEAT_FAULT_STATUS    55u
#define TCU_SIG_CVC_HEARTBEAT_OPERATING_MODE    56u
#define TCU_SIG_DTC_BROADCAST_DTC_NUMBER    57u
#define TCU_SIG_DTC_BROADCAST_DTC_STATUS    58u
#define TCU_SIG_DTC_BROADCAST_ECU_SOURCE    59u
#define TCU_SIG_DTC_BROADCAST_FREEZE_FRAME_0    60u
#define TCU_SIG_DTC_BROADCAST_FREEZE_FRAME_1    61u
#define TCU_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    62u
#define TCU_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK    63u
#define TCU_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK    64u
#define TCU_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK    65u
#define TCU_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK    66u
#define TCU_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK    67u
#define TCU_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    68u
#define TCU_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    69u
#define TCU_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    70u
#define TCU_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    71u
#define TCU_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    72u
#define TCU_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    73u
#define TCU_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    74u
#define TCU_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    75u
#define TCU_SIG_FZC_HEARTBEAT_ECU_ID    76u
#define TCU_SIG_FZC_HEARTBEAT_FAULT_STATUS    77u
#define TCU_SIG_FZC_HEARTBEAT_OPERATING_MODE    78u
#define TCU_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    79u
#define TCU_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    80u
#define TCU_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    81u
#define TCU_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    82u
#define TCU_SIG_ICU_HEARTBEAT_ECU_ID    83u
#define TCU_SIG_INDICATOR_STATE_BLINK_STATE    84u
#define TCU_SIG_INDICATOR_STATE_HAZARD_ACTIVE    85u
#define TCU_SIG_INDICATOR_STATE_LEFT_INDICATOR    86u
#define TCU_SIG_INDICATOR_STATE_RIGHT_INDICATOR    87u
#define TCU_SIG_LIDAR_DISTANCE_DISTANCE_CM    88u
#define TCU_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER    89u
#define TCU_SIG_LIDAR_DISTANCE_E_2_E_CRC_8    90u
#define TCU_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID    91u
#define TCU_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE    92u
#define TCU_SIG_LIDAR_DISTANCE_SENSOR_STATUS    93u
#define TCU_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH    94u
#define TCU_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON    95u
#define TCU_SIG_LIGHT_STATUS_FOG_LIGHT_ON    96u
#define TCU_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL    97u
#define TCU_SIG_LIGHT_STATUS_HEADLIGHT_ON    98u
#define TCU_SIG_LIGHT_STATUS_TAIL_LIGHT_ON    99u
#define TCU_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   100u
#define TCU_SIG_MOTOR_CURRENT_CURRENT_M_A   101u
#define TCU_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   102u
#define TCU_SIG_MOTOR_CURRENT_E_2_E_CRC_8   103u
#define TCU_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   104u
#define TCU_SIG_MOTOR_CURRENT_MOTOR_ENABLE   105u
#define TCU_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   106u
#define TCU_SIG_MOTOR_CURRENT_TORQUE_ECHO   107u
#define TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   108u
#define TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   109u
#define TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   110u
#define TCU_SIG_MOTOR_CUTOFF_REQ_REASON   111u
#define TCU_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   112u
#define TCU_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   113u
#define TCU_SIG_MOTOR_STATUS_E_2_E_CRC_8   114u
#define TCU_SIG_MOTOR_STATUS_E_2_E_DATA_ID   115u
#define TCU_SIG_MOTOR_STATUS_MOTOR_DIRECTION   116u
#define TCU_SIG_MOTOR_STATUS_MOTOR_ENABLE   117u
#define TCU_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   118u
#define TCU_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   119u
#define TCU_SIG_MOTOR_STATUS_TORQUE_ECHO   120u
#define TCU_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   121u
#define TCU_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   122u
#define TCU_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   123u
#define TCU_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   124u
#define TCU_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   125u
#define TCU_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   126u
#define TCU_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER   127u
#define TCU_SIG_RZC_HEARTBEAT_E_2_E_CRC_8   128u
#define TCU_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID   129u
#define TCU_SIG_RZC_HEARTBEAT_ECU_ID   130u
#define TCU_SIG_RZC_HEARTBEAT_FAULT_STATUS   131u
#define TCU_SIG_RZC_HEARTBEAT_OPERATING_MODE   132u
#define TCU_SIG_SC_STATUS_ECU_HEALTH   133u
#define TCU_SIG_SC_STATUS_FAULT_REASON   134u
#define TCU_SIG_SC_STATUS_RELAY_STATE   135u
#define TCU_SIG_SC_STATUS_SC_ALIVE_COUNTER   136u
#define TCU_SIG_SC_STATUS_SC_CRC_8   137u
#define TCU_SIG_SC_STATUS_SC_FAULT_FLAGS   138u
#define TCU_SIG_SC_STATUS_SC_MODE   139u
#define TCU_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER   140u
#define TCU_SIG_STEER_COMMAND_E_2_E_CRC_8   141u
#define TCU_SIG_STEER_COMMAND_E_2_E_DATA_ID   142u
#define TCU_SIG_STEER_COMMAND_STEER_ANGLE_CMD   143u
#define TCU_SIG_STEER_COMMAND_STEER_RATE_LIMIT   144u
#define TCU_SIG_STEER_COMMAND_VEHICLE_STATE   145u
#define TCU_SIG_STEERING_STATUS_ACTUAL_ANGLE   146u
#define TCU_SIG_STEERING_STATUS_COMMANDED_ANGLE   147u
#define TCU_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER   148u
#define TCU_SIG_STEERING_STATUS_E_2_E_CRC_8   149u
#define TCU_SIG_STEERING_STATUS_E_2_E_DATA_ID   150u
#define TCU_SIG_STEERING_STATUS_SERVO_CURRENT_M_A   151u
#define TCU_SIG_STEERING_STATUS_STEER_FAULT_STATUS   152u
#define TCU_SIG_STEERING_STATUS_STEER_MODE   153u
#define TCU_SIG_TCU_HEARTBEAT_ALIVE_COUNTER   154u
#define TCU_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER   155u
#define TCU_SIG_TCU_HEARTBEAT_E_2_E_CRC_8   156u
#define TCU_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID   157u
#define TCU_SIG_TCU_HEARTBEAT_ECU_ID   158u
#define TCU_SIG_TORQUE_REQUEST_DIRECTION   159u
#define TCU_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER   160u
#define TCU_SIG_TORQUE_REQUEST_E_2_E_CRC_8   161u
#define TCU_SIG_TORQUE_REQUEST_E_2_E_DATA_ID   162u
#define TCU_SIG_TORQUE_REQUEST_PEDAL_FAULT   163u
#define TCU_SIG_TORQUE_REQUEST_PEDAL_POSITION_1   164u
#define TCU_SIG_TORQUE_REQUEST_PEDAL_POSITION_2   165u
#define TCU_SIG_TORQUE_REQUEST_TORQUE_REQUEST   166u
#define TCU_SIG_UDS_FUNC_REQUEST_UDS_DATA   167u
#define TCU_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   168u
#define TCU_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   169u
#define TCU_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   170u
#define TCU_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   171u
#define TCU_SIG_UDS_RESP_CVC_UDS_DATA   172u
#define TCU_SIG_UDS_RESP_FZC_UDS_DATA   173u
#define TCU_SIG_UDS_RESP_RZC_UDS_DATA   174u
#define TCU_SIG_UDS_RESP_TCU_UDS_DATA   175u
#define TCU_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER   176u
#define TCU_SIG_VEHICLE_STATE_E_2_E_CRC_8   177u
#define TCU_SIG_VEHICLE_STATE_E_2_E_DATA_ID   178u
#define TCU_SIG_VEHICLE_STATE_FAULT_MASK   179u
#define TCU_SIG_VEHICLE_STATE_SPEED_LIMIT   180u
#define TCU_SIG_VEHICLE_STATE_TORQUE_LIMIT   181u
#define TCU_SIG_VEHICLE_STATE_VEHICLE_STATE   182u
#define TCU_SIG_COUNT   183u

/* ====================================================================
 * Com TX PDU IDs
 * ==================================================================== */

#define TCU_COM_TX_TCU_HEARTBEAT     0u   /* CAN 0x015 */
#define TCU_COM_TX_DTC_BROADCAST     1u   /* CAN 0x500 */
#define TCU_COM_TX_UDS_RESP_TCU     2u   /* CAN 0x644 */

/* ====================================================================
 * Com RX PDU IDs
 * ==================================================================== */

#define TCU_COM_RX_ESTOP_BROADCAST     0u   /* CAN 0x001 */
#define TCU_COM_RX_CVC_HEARTBEAT     1u   /* CAN 0x010 */
#define TCU_COM_RX_FZC_HEARTBEAT     2u   /* CAN 0x011 */
#define TCU_COM_RX_RZC_HEARTBEAT     3u   /* CAN 0x012 */
#define TCU_COM_RX_SC_STATUS     4u   /* CAN 0x013 */
#define TCU_COM_RX_ICU_HEARTBEAT     5u   /* CAN 0x014 */
#define TCU_COM_RX_BCM_HEARTBEAT     6u   /* CAN 0x016 */
#define TCU_COM_RX_VEHICLE_STATE     7u   /* CAN 0x100 */
#define TCU_COM_RX_TORQUE_REQUEST     8u   /* CAN 0x101 */
#define TCU_COM_RX_STEER_COMMAND     9u   /* CAN 0x102 */
#define TCU_COM_RX_BRAKE_COMMAND    10u   /* CAN 0x103 */
#define TCU_COM_RX_STEERING_STATUS    11u   /* CAN 0x200 */
#define TCU_COM_RX_BRAKE_STATUS    12u   /* CAN 0x201 */
#define TCU_COM_RX_BRAKE_FAULT    13u   /* CAN 0x210 */
#define TCU_COM_RX_MOTOR_CUTOFF_REQ    14u   /* CAN 0x211 */
#define TCU_COM_RX_LIDAR_DISTANCE    15u   /* CAN 0x220 */
#define TCU_COM_RX_MOTOR_STATUS    16u   /* CAN 0x300 */
#define TCU_COM_RX_MOTOR_CURRENT    17u   /* CAN 0x301 */
#define TCU_COM_RX_MOTOR_TEMPERATURE    18u   /* CAN 0x302 */
#define TCU_COM_RX_BATTERY_STATUS    19u   /* CAN 0x303 */
#define TCU_COM_RX_BODY_CONTROL_CMD    20u   /* CAN 0x350 */
#define TCU_COM_RX_LIGHT_STATUS    21u   /* CAN 0x400 */
#define TCU_COM_RX_INDICATOR_STATE    22u   /* CAN 0x401 */
#define TCU_COM_RX_DOOR_LOCK_STATUS    23u   /* CAN 0x402 */
#define TCU_COM_RX_DTC_BROADCAST    24u   /* CAN 0x500 */
#define TCU_COM_RX_UDS_FUNC_REQUEST    25u   /* CAN 0x7DF */
#define TCU_COM_RX_UDS_PHYS_REQ_CVC    26u   /* CAN 0x7E0 */
#define TCU_COM_RX_UDS_PHYS_REQ_FZC    27u   /* CAN 0x7E1 */
#define TCU_COM_RX_UDS_PHYS_REQ_RZC    28u   /* CAN 0x7E2 */
#define TCU_COM_RX_UDS_PHYS_REQ_TCU    29u   /* CAN 0x7E3 */
#define TCU_COM_RX_UDS_RESP_CVC    30u   /* CAN 0x7E8 */
#define TCU_COM_RX_UDS_RESP_FZC    31u   /* CAN 0x7E9 */
#define TCU_COM_RX_UDS_RESP_RZC    32u   /* CAN 0x7EA */

/* ====================================================================
 * Com Signal IDs (index into Com signal config table)
 * Use these instead of hardcoded numbers in Com_SendSignal/Com_ReceiveSignal
 * ==================================================================== */

#define TCU_COM_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID     0u   /* TX TCU_Heartbeat */
#define TCU_COM_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER     1u   /* TX TCU_Heartbeat */
#define TCU_COM_SIG_TCU_HEARTBEAT_E_2_E_CRC_8     2u   /* TX TCU_Heartbeat */
#define TCU_COM_SIG_TCU_HEARTBEAT_ALIVE_COUNTER     3u   /* TX TCU_Heartbeat */
#define TCU_COM_SIG_TCU_HEARTBEAT_ECU_ID     4u   /* TX TCU_Heartbeat */
#define TCU_COM_SIG_DTC_BROADCAST_DTC_NUMBER     5u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_DTC_BROADCAST_DTC_STATUS     6u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_DTC_BROADCAST_ECU_SOURCE     7u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_DTC_BROADCAST_OCCURRENCE_COUNT     8u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_0     9u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_1    10u   /* TX DTC_Broadcast */
#define TCU_COM_SIG_UDS_RESP_TCU_UDS_DATA    11u   /* TX UDS_Resp_TCU */
#define TCU_COM_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    12u   /* RX EStop_Broadcast */
#define TCU_COM_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    13u   /* RX EStop_Broadcast */
#define TCU_COM_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    14u   /* RX EStop_Broadcast */
#define TCU_COM_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    15u   /* RX EStop_Broadcast */
#define TCU_COM_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    16u   /* RX EStop_Broadcast */
#define TCU_COM_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    17u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    18u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    19u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_CVC_HEARTBEAT_ECU_ID    20u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_CVC_HEARTBEAT_OPERATING_MODE    21u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_CVC_HEARTBEAT_FAULT_STATUS    22u   /* RX CVC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    23u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    24u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    25u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_ECU_ID    26u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_OPERATING_MODE    27u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_FZC_HEARTBEAT_FAULT_STATUS    28u   /* RX FZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID    29u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    30u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_E_2_E_CRC_8    31u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_ECU_ID    32u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_OPERATING_MODE    33u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_RZC_HEARTBEAT_FAULT_STATUS    34u   /* RX RZC_Heartbeat */
#define TCU_COM_SIG_SC_STATUS_SC_ALIVE_COUNTER    35u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_SC_CRC_8    36u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_SC_MODE    37u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_SC_FAULT_FLAGS    38u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_ECU_HEALTH    39u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_FAULT_REASON    40u   /* RX SC_Status */
#define TCU_COM_SIG_SC_STATUS_RELAY_STATE    41u   /* RX SC_Status */
#define TCU_COM_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    42u   /* RX ICU_Heartbeat */
#define TCU_COM_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    43u   /* RX ICU_Heartbeat */
#define TCU_COM_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    44u   /* RX ICU_Heartbeat */
#define TCU_COM_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    45u   /* RX ICU_Heartbeat */
#define TCU_COM_SIG_ICU_HEARTBEAT_ECU_ID    46u   /* RX ICU_Heartbeat */
#define TCU_COM_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    47u   /* RX BCM_Heartbeat */
#define TCU_COM_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    48u   /* RX BCM_Heartbeat */
#define TCU_COM_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    49u   /* RX BCM_Heartbeat */
#define TCU_COM_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    50u   /* RX BCM_Heartbeat */
#define TCU_COM_SIG_BCM_HEARTBEAT_ECU_ID    51u   /* RX BCM_Heartbeat */
#define TCU_COM_SIG_VEHICLE_STATE_E_2_E_DATA_ID    52u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER    53u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_E_2_E_CRC_8    54u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_VEHICLE_STATE    55u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_FAULT_MASK    56u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_TORQUE_LIMIT    57u   /* RX Vehicle_State */
#define TCU_COM_SIG_VEHICLE_STATE_SPEED_LIMIT    58u   /* RX Vehicle_State */
#define TCU_COM_SIG_TORQUE_REQUEST_E_2_E_DATA_ID    59u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER    60u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_E_2_E_CRC_8    61u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_TORQUE_REQUEST    62u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_DIRECTION    63u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_1    64u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_2    65u   /* RX Torque_Request */
#define TCU_COM_SIG_TORQUE_REQUEST_PEDAL_FAULT    66u   /* RX Torque_Request */
#define TCU_COM_SIG_STEER_COMMAND_E_2_E_DATA_ID    67u   /* RX Steer_Command */
#define TCU_COM_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER    68u   /* RX Steer_Command */
#define TCU_COM_SIG_STEER_COMMAND_E_2_E_CRC_8    69u   /* RX Steer_Command */
#define TCU_COM_SIG_STEER_COMMAND_STEER_ANGLE_CMD    70u   /* RX Steer_Command */
#define TCU_COM_SIG_STEER_COMMAND_STEER_RATE_LIMIT    71u   /* RX Steer_Command */
#define TCU_COM_SIG_STEER_COMMAND_VEHICLE_STATE    72u   /* RX Steer_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    73u   /* RX Brake_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    74u   /* RX Brake_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_E_2_E_CRC_8    75u   /* RX Brake_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    76u   /* RX Brake_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_BRAKE_MODE    77u   /* RX Brake_Command */
#define TCU_COM_SIG_BRAKE_COMMAND_VEHICLE_STATE    78u   /* RX Brake_Command */
#define TCU_COM_SIG_STEERING_STATUS_E_2_E_DATA_ID    79u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER    80u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_E_2_E_CRC_8    81u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_ACTUAL_ANGLE    82u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_COMMANDED_ANGLE    83u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_STEER_FAULT_STATUS    84u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_STEER_MODE    85u   /* RX Steering_Status */
#define TCU_COM_SIG_STEERING_STATUS_SERVO_CURRENT_M_A    86u   /* RX Steering_Status */
#define TCU_COM_SIG_BRAKE_STATUS_E_2_E_DATA_ID    87u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    88u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_E_2_E_CRC_8    89u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_BRAKE_POSITION    90u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    91u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    92u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    93u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_STATUS_BRAKE_MODE    94u   /* RX Brake_Status */
#define TCU_COM_SIG_BRAKE_FAULT_E_2_E_DATA_ID    95u   /* RX Brake_Fault */
#define TCU_COM_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    96u   /* RX Brake_Fault */
#define TCU_COM_SIG_BRAKE_FAULT_E_2_E_CRC_8    97u   /* RX Brake_Fault */
#define TCU_COM_SIG_BRAKE_FAULT_FAULT_TYPE    98u   /* RX Brake_Fault */
#define TCU_COM_SIG_BRAKE_FAULT_COMMANDED_BRAKE    99u   /* RX Brake_Fault */
#define TCU_COM_SIG_BRAKE_FAULT_MEASURED_BRAKE   100u   /* RX Brake_Fault */
#define TCU_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   101u   /* RX Motor_Cutoff_Req */
#define TCU_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   102u   /* RX Motor_Cutoff_Req */
#define TCU_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   103u   /* RX Motor_Cutoff_Req */
#define TCU_COM_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   104u   /* RX Motor_Cutoff_Req */
#define TCU_COM_SIG_MOTOR_CUTOFF_REQ_REASON   105u   /* RX Motor_Cutoff_Req */
#define TCU_COM_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID   106u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER   107u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_E_2_E_CRC_8   108u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_DISTANCE_CM   109u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH   110u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE   111u   /* RX Lidar_Distance */
#define TCU_COM_SIG_LIDAR_DISTANCE_SENSOR_STATUS   112u   /* RX Lidar_Distance */
#define TCU_COM_SIG_MOTOR_STATUS_E_2_E_DATA_ID   113u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   114u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_E_2_E_CRC_8   115u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_TORQUE_ECHO   116u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   117u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_MOTOR_DIRECTION   118u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_MOTOR_ENABLE   119u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   120u   /* RX Motor_Status */
#define TCU_COM_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   121u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   122u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_E_2_E_CRC_8   123u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_CURRENT_M_A   124u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   125u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_MOTOR_ENABLE   126u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   127u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_CURRENT_TORQUE_ECHO   128u   /* RX Motor_Current */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   129u   /* RX Motor_Temperature */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   130u   /* RX Motor_Temperature */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   131u   /* RX Motor_Temperature */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   132u   /* RX Motor_Temperature */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   133u   /* RX Motor_Temperature */
#define TCU_COM_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   134u   /* RX Motor_Temperature */
#define TCU_COM_SIG_BATTERY_STATUS_E_2_E_DATA_ID   135u   /* RX Battery_Status */
#define TCU_COM_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER   136u   /* RX Battery_Status */
#define TCU_COM_SIG_BATTERY_STATUS_E_2_E_CRC_8   137u   /* RX Battery_Status */
#define TCU_COM_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V   138u   /* RX Battery_Status */
#define TCU_COM_SIG_BATTERY_STATUS_BATTERY_STATUS   139u   /* RX Battery_Status */
#define TCU_COM_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD   140u   /* RX Body_Control_Cmd */
#define TCU_COM_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD   141u   /* RX Body_Control_Cmd */
#define TCU_COM_SIG_BODY_CONTROL_CMD_HAZARD_CMD   142u   /* RX Body_Control_Cmd */
#define TCU_COM_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD   143u   /* RX Body_Control_Cmd */
#define TCU_COM_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD   144u   /* RX Body_Control_Cmd */
#define TCU_COM_SIG_LIGHT_STATUS_HEADLIGHT_ON   145u   /* RX Light_Status */
#define TCU_COM_SIG_LIGHT_STATUS_TAIL_LIGHT_ON   146u   /* RX Light_Status */
#define TCU_COM_SIG_LIGHT_STATUS_FOG_LIGHT_ON   147u   /* RX Light_Status */
#define TCU_COM_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON   148u   /* RX Light_Status */
#define TCU_COM_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL   149u   /* RX Light_Status */
#define TCU_COM_SIG_INDICATOR_STATE_LEFT_INDICATOR   150u   /* RX Indicator_State */
#define TCU_COM_SIG_INDICATOR_STATE_RIGHT_INDICATOR   151u   /* RX Indicator_State */
#define TCU_COM_SIG_INDICATOR_STATE_HAZARD_ACTIVE   152u   /* RX Indicator_State */
#define TCU_COM_SIG_INDICATOR_STATE_BLINK_STATE   153u   /* RX Indicator_State */
#define TCU_COM_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK   154u   /* RX Door_Lock_Status */
#define TCU_COM_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK   155u   /* RX Door_Lock_Status */
#define TCU_COM_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK   156u   /* RX Door_Lock_Status */
#define TCU_COM_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK   157u   /* RX Door_Lock_Status */
#define TCU_COM_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK   158u   /* RX Door_Lock_Status */
#define TCU_COM_SIG_UDS_FUNC_REQUEST_UDS_DATA   159u   /* RX UDS_Func_Request */
#define TCU_COM_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   160u   /* RX UDS_Phys_Req_CVC */
#define TCU_COM_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   161u   /* RX UDS_Phys_Req_FZC */
#define TCU_COM_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   162u   /* RX UDS_Phys_Req_RZC */
#define TCU_COM_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   163u   /* RX UDS_Phys_Req_TCU */
#define TCU_COM_SIG_UDS_RESP_CVC_UDS_DATA   164u   /* RX UDS_Resp_CVC */
#define TCU_COM_SIG_UDS_RESP_FZC_UDS_DATA   165u   /* RX UDS_Resp_FZC */
#define TCU_COM_SIG_UDS_RESP_RZC_UDS_DATA   166u   /* RX UDS_Resp_RZC */
#define TCU_COM_SIG_COUNT   167u

/* ====================================================================
 * DTC Event IDs (Dem_EventIdType)
 * ==================================================================== */

#define TCU_DTC_AGING_CLEAR_CYCLES     0u

/* ====================================================================
 * E2E Data IDs
 * ==================================================================== */

#define TCU_E2E_HEARTBEAT_DATA_ID  0x41u

/* ====================================================================
 * Thresholds
 * ==================================================================== */

#define TCU_RTE_PERIOD_MS    10u
#define TCU_COMM_TIMEOUT   200u

/* ====================================================================
 * Application-specific constants (hand-authored, not generated)
 * ==================================================================== */
#if __has_include("Tcu_App.h")
#include "Tcu_App.h"
#endif

#endif /* TCU_CFG_H */
