/**
 * @file    Rte_Cfg_Tcu.c
 * @brief   RTE configuration for TCU — signal table and runnable table
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Rte.h"
#include "Tcu_Cfg.h"

/* ==================================================================
 * Forward declarations for SWC runnables
 * ================================================================== */

extern void Swc_DtcStore_Init(void);
extern void Swc_Obd2Pids_Init(void);
extern void Swc_UdsServer_Init(void);

/* ==================================================================
 * Signal Configuration Table
 * ================================================================== */

static const Rte_SignalConfigType tcu_signal_config[TCU_SIG_COUNT] = {
    /* BSW well-known signals (0-15) — initial values */
    {  0u, 0u },   /* RTE_SIG_TORQUE_REQUEST */
    {  1u, 0u },   /* RTE_SIG_STEERING_ANGLE */
    {  2u, 0u },   /* RTE_SIG_VEHICLE_SPEED */
    {  3u, 0u },   /* RTE_SIG_BRAKE_PRESSURE */
    {  4u, 0u },   /* RTE_SIG_MOTOR_STATUS */
    {  5u, 0u },   /* RTE_SIG_BATTERY_VOLTAGE */
    {  6u, 0u },   /* RTE_SIG_BATTERY_CURRENT */
    {  7u, 0u },   /* RTE_SIG_MOTOR_TEMP */
    {  8u, 0u },   /* RTE_SIG_ESTOP_STATUS */
    {  9u, 0u },   /* RTE_SIG_HEARTBEAT */
    { 10u, 0u },   /* Reserved                */
    { 11u, 0u },   /* Reserved                */
    { 12u, 0u },   /* Reserved                */
    { 13u, 0u },   /* Reserved                */
    { 14u, 0u },   /* Reserved                */
    { 15u, 0u },   /* Reserved                */

    /* TCU application signals (16+) */
    { TCU_SIG_BCM_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 16: BCM_Heartbeat_AliveCounter */
    { TCU_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 17: BCM_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_BCM_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 18: BCM_Heartbeat_E2E_CRC8 */
    { TCU_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 19: BCM_Heartbeat_E2E_DataID */
    { TCU_SIG_BCM_HEARTBEAT_ECU_ID, 0u },   /* 20: BCM_Heartbeat_ECU_ID */
    { TCU_SIG_BATTERY_STATUS_BATTERY_STATUS, 0u },   /* 21: Battery_Status_BatteryStatus */
    { TCU_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, 0u },   /* 22: Battery_Status_BatteryVoltage_mV */
    { TCU_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 23: Battery_Status_E2E_AliveCounter */
    { TCU_SIG_BATTERY_STATUS_E_2_E_CRC_8, 0u },   /* 24: Battery_Status_E2E_CRC8 */
    { TCU_SIG_BATTERY_STATUS_E_2_E_DATA_ID, 0u },   /* 25: Battery_Status_E2E_DataID */
    { TCU_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, 0u },   /* 26: Body_Control_Cmd_DoorLockCmd */
    { TCU_SIG_BODY_CONTROL_CMD_HAZARD_CMD, 0u },   /* 27: Body_Control_Cmd_HazardCmd */
    { TCU_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, 0u },   /* 28: Body_Control_Cmd_HeadlightCmd */
    { TCU_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD, 0u },   /* 29: Body_Control_Cmd_TailLightCmd */
    { TCU_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, 0u },   /* 30: Body_Control_Cmd_TurnSignalCmd */
    { TCU_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD, 0u },   /* 31: Brake_Command_BrakeForceCmd */
    { TCU_SIG_BRAKE_COMMAND_BRAKE_MODE, 0u },   /* 32: Brake_Command_BrakeMode */
    { TCU_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 33: Brake_Command_E2E_AliveCounter */
    { TCU_SIG_BRAKE_COMMAND_E_2_E_CRC_8, 0u },   /* 34: Brake_Command_E2E_CRC8 */
    { TCU_SIG_BRAKE_COMMAND_E_2_E_DATA_ID, 0u },   /* 35: Brake_Command_E2E_DataID */
    { TCU_SIG_BRAKE_COMMAND_VEHICLE_STATE, 0u },   /* 36: Brake_Command_VehicleState */
    { TCU_SIG_BRAKE_FAULT_COMMANDED_BRAKE, 0u },   /* 37: Brake_Fault_CommandedBrake */
    { TCU_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER, 0u },   /* 38: Brake_Fault_E2E_AliveCounter */
    { TCU_SIG_BRAKE_FAULT_E_2_E_CRC_8, 0u },   /* 39: Brake_Fault_E2E_CRC8 */
    { TCU_SIG_BRAKE_FAULT_E_2_E_DATA_ID, 0u },   /* 40: Brake_Fault_E2E_DataID */
    { TCU_SIG_BRAKE_FAULT_FAULT_TYPE, 0u },   /* 41: Brake_Fault_FaultType */
    { TCU_SIG_BRAKE_FAULT_MEASURED_BRAKE, 0u },   /* 42: Brake_Fault_MeasuredBrake */
    { TCU_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO, 0u },   /* 43: Brake_Status_BrakeCommandEcho */
    { TCU_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, 0u },   /* 44: Brake_Status_BrakeFaultStatus */
    { TCU_SIG_BRAKE_STATUS_BRAKE_MODE, 0u },   /* 45: Brake_Status_BrakeMode */
    { TCU_SIG_BRAKE_STATUS_BRAKE_POSITION, 0u },   /* 46: Brake_Status_BrakePosition */
    { TCU_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 47: Brake_Status_E2E_AliveCounter */
    { TCU_SIG_BRAKE_STATUS_E_2_E_CRC_8, 0u },   /* 48: Brake_Status_E2E_CRC8 */
    { TCU_SIG_BRAKE_STATUS_E_2_E_DATA_ID, 0u },   /* 49: Brake_Status_E2E_DataID */
    { TCU_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A, 0u },   /* 50: Brake_Status_ServoCurrent_mA */
    { TCU_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 51: CVC_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_CVC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 52: CVC_Heartbeat_E2E_CRC8 */
    { TCU_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 53: CVC_Heartbeat_E2E_DataID */
    { TCU_SIG_CVC_HEARTBEAT_ECU_ID, 0u },   /* 54: CVC_Heartbeat_ECU_ID */
    { TCU_SIG_CVC_HEARTBEAT_FAULT_STATUS, 0u },   /* 55: CVC_Heartbeat_FaultStatus */
    { TCU_SIG_CVC_HEARTBEAT_OPERATING_MODE, 0u },   /* 56: CVC_Heartbeat_OperatingMode */
    { TCU_SIG_DTC_BROADCAST_DTC_NUMBER, 0u },   /* 57: DTC_Broadcast_DTC_Number */
    { TCU_SIG_DTC_BROADCAST_DTC_STATUS, 0u },   /* 58: DTC_Broadcast_DTC_Status */
    { TCU_SIG_DTC_BROADCAST_ECU_SOURCE, 0u },   /* 59: DTC_Broadcast_ECU_Source */
    { TCU_SIG_DTC_BROADCAST_FREEZE_FRAME_0, 0u },   /* 60: DTC_Broadcast_FreezeFrame0 */
    { TCU_SIG_DTC_BROADCAST_FREEZE_FRAME_1, 0u },   /* 61: DTC_Broadcast_FreezeFrame1 */
    { TCU_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, 0u },   /* 62: DTC_Broadcast_OccurrenceCount */
    { TCU_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, 0u },   /* 63: Door_Lock_Status_CentralLock */
    { TCU_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, 0u },   /* 64: Door_Lock_Status_FrontLeftLock */
    { TCU_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, 0u },   /* 65: Door_Lock_Status_FrontRightLock */
    { TCU_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, 0u },   /* 66: Door_Lock_Status_RearLeftLock */
    { TCU_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, 0u },   /* 67: Door_Lock_Status_RearRightLock */
    { TCU_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, 0u },   /* 68: EStop_Broadcast_E2E_AliveCounter */
    { TCU_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, 0u },   /* 69: EStop_Broadcast_E2E_CRC8 */
    { TCU_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, 0u },   /* 70: EStop_Broadcast_E2E_DataID */
    { TCU_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE, 0u },   /* 71: EStop_Broadcast_EStop_Active */
    { TCU_SIG_ESTOP_BROADCAST_ESTOP_SOURCE, 0u },   /* 72: EStop_Broadcast_EStop_Source */
    { TCU_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 73: FZC_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_FZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 74: FZC_Heartbeat_E2E_CRC8 */
    { TCU_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 75: FZC_Heartbeat_E2E_DataID */
    { TCU_SIG_FZC_HEARTBEAT_ECU_ID, 0u },   /* 76: FZC_Heartbeat_ECU_ID */
    { TCU_SIG_FZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 77: FZC_Heartbeat_FaultStatus */
    { TCU_SIG_FZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 78: FZC_Heartbeat_OperatingMode */
    { TCU_SIG_ICU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 79: ICU_Heartbeat_AliveCounter */
    { TCU_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 80: ICU_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_ICU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 81: ICU_Heartbeat_E2E_CRC8 */
    { TCU_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 82: ICU_Heartbeat_E2E_DataID */
    { TCU_SIG_ICU_HEARTBEAT_ECU_ID, 0u },   /* 83: ICU_Heartbeat_ECU_ID */
    { TCU_SIG_INDICATOR_STATE_BLINK_STATE, 0u },   /* 84: Indicator_State_BlinkState */
    { TCU_SIG_INDICATOR_STATE_HAZARD_ACTIVE, 0u },   /* 85: Indicator_State_HazardActive */
    { TCU_SIG_INDICATOR_STATE_LEFT_INDICATOR, 0u },   /* 86: Indicator_State_LeftIndicator */
    { TCU_SIG_INDICATOR_STATE_RIGHT_INDICATOR, 0u },   /* 87: Indicator_State_RightIndicator */
    { TCU_SIG_LIDAR_DISTANCE_DISTANCE_CM, 0u },   /* 88: Lidar_Distance_Distance_cm */
    { TCU_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER, 0u },   /* 89: Lidar_Distance_E2E_AliveCounter */
    { TCU_SIG_LIDAR_DISTANCE_E_2_E_CRC_8, 0u },   /* 90: Lidar_Distance_E2E_CRC8 */
    { TCU_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID, 0u },   /* 91: Lidar_Distance_E2E_DataID */
    { TCU_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, 0u },   /* 92: Lidar_Distance_ObstacleZone */
    { TCU_SIG_LIDAR_DISTANCE_SENSOR_STATUS, 0u },   /* 93: Lidar_Distance_SensorStatus */
    { TCU_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, 0u },   /* 94: Lidar_Distance_SignalStrength */
    { TCU_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, 0u },   /* 95: Light_Status_BrakeLightOn */
    { TCU_SIG_LIGHT_STATUS_FOG_LIGHT_ON, 0u },   /* 96: Light_Status_FogLightOn */
    { TCU_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, 0u },   /* 97: Light_Status_HeadlightLevel */
    { TCU_SIG_LIGHT_STATUS_HEADLIGHT_ON, 0u },   /* 98: Light_Status_HeadlightOn */
    { TCU_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, 0u },   /* 99: Light_Status_TailLightOn */
    { TCU_SIG_MOTOR_CURRENT_CURRENT_DIRECTION, 0u },   /* 100: Motor_Current_CurrentDirection */
    { TCU_SIG_MOTOR_CURRENT_CURRENT_M_A, 0u },   /* 101: Motor_Current_Current_mA */
    { TCU_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER, 0u },   /* 102: Motor_Current_E2E_AliveCounter */
    { TCU_SIG_MOTOR_CURRENT_E_2_E_CRC_8, 0u },   /* 103: Motor_Current_E2E_CRC8 */
    { TCU_SIG_MOTOR_CURRENT_E_2_E_DATA_ID, 0u },   /* 104: Motor_Current_E2E_DataID */
    { TCU_SIG_MOTOR_CURRENT_MOTOR_ENABLE, 0u },   /* 105: Motor_Current_MotorEnable */
    { TCU_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG, 0u },   /* 106: Motor_Current_OvercurrentFlag */
    { TCU_SIG_MOTOR_CURRENT_TORQUE_ECHO, 0u },   /* 107: Motor_Current_TorqueEcho */
    { TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER, 0u },   /* 108: Motor_Cutoff_Req_E2E_AliveCounter */
    { TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8, 0u },   /* 109: Motor_Cutoff_Req_E2E_CRC8 */
    { TCU_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID, 0u },   /* 110: Motor_Cutoff_Req_E2E_DataID */
    { TCU_SIG_MOTOR_CUTOFF_REQ_REASON, 0u },   /* 111: Motor_Cutoff_Req_Reason */
    { TCU_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, 0u },   /* 112: Motor_Cutoff_Req_RequestType */
    { TCU_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 113: Motor_Status_E2E_AliveCounter */
    { TCU_SIG_MOTOR_STATUS_E_2_E_CRC_8, 0u },   /* 114: Motor_Status_E2E_CRC8 */
    { TCU_SIG_MOTOR_STATUS_E_2_E_DATA_ID, 0u },   /* 115: Motor_Status_E2E_DataID */
    { TCU_SIG_MOTOR_STATUS_MOTOR_DIRECTION, 0u },   /* 116: Motor_Status_MotorDirection */
    { TCU_SIG_MOTOR_STATUS_MOTOR_ENABLE, 0u },   /* 117: Motor_Status_MotorEnable */
    { TCU_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, 0u },   /* 118: Motor_Status_MotorFaultStatus */
    { TCU_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, 0u },   /* 119: Motor_Status_MotorSpeed_RPM */
    { TCU_SIG_MOTOR_STATUS_TORQUE_ECHO, 0u },   /* 120: Motor_Status_TorqueEcho */
    { TCU_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT, 0u },   /* 121: Motor_Temperature_DeratingPercent */
    { TCU_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER, 0u },   /* 122: Motor_Temperature_E2E_AliveCounter */
    { TCU_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8, 0u },   /* 123: Motor_Temperature_E2E_CRC8 */
    { TCU_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID, 0u },   /* 124: Motor_Temperature_E2E_DataID */
    { TCU_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C, 0u },   /* 125: Motor_Temperature_WindingTemp1_C */
    { TCU_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C, 0u },   /* 126: Motor_Temperature_WindingTemp2_C */
    { TCU_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 127: RZC_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_RZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 128: RZC_Heartbeat_E2E_CRC8 */
    { TCU_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 129: RZC_Heartbeat_E2E_DataID */
    { TCU_SIG_RZC_HEARTBEAT_ECU_ID, 0u },   /* 130: RZC_Heartbeat_ECU_ID */
    { TCU_SIG_RZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 131: RZC_Heartbeat_FaultStatus */
    { TCU_SIG_RZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 132: RZC_Heartbeat_OperatingMode */
    { TCU_SIG_SC_STATUS_ECU_HEALTH, 0u },   /* 133: SC_Status_ECU_Health */
    { TCU_SIG_SC_STATUS_FAULT_REASON, 0u },   /* 134: SC_Status_FaultReason */
    { TCU_SIG_SC_STATUS_RELAY_STATE, 0u },   /* 135: SC_Status_RelayState */
    { TCU_SIG_SC_STATUS_SC_ALIVE_COUNTER, 0u },   /* 136: SC_Status_SC_AliveCounter */
    { TCU_SIG_SC_STATUS_SC_CRC_8, 0u },   /* 137: SC_Status_SC_CRC8 */
    { TCU_SIG_SC_STATUS_SC_FAULT_FLAGS, 0u },   /* 138: SC_Status_SC_FaultFlags */
    { TCU_SIG_SC_STATUS_SC_MODE, 0u },   /* 139: SC_Status_SC_Mode */
    { TCU_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 140: Steer_Command_E2E_AliveCounter */
    { TCU_SIG_STEER_COMMAND_E_2_E_CRC_8, 0u },   /* 141: Steer_Command_E2E_CRC8 */
    { TCU_SIG_STEER_COMMAND_E_2_E_DATA_ID, 0u },   /* 142: Steer_Command_E2E_DataID */
    { TCU_SIG_STEER_COMMAND_STEER_ANGLE_CMD, 0u },   /* 143: Steer_Command_SteerAngleCmd */
    { TCU_SIG_STEER_COMMAND_STEER_RATE_LIMIT, 0u },   /* 144: Steer_Command_SteerRateLimit */
    { TCU_SIG_STEER_COMMAND_VEHICLE_STATE, 0u },   /* 145: Steer_Command_VehicleState */
    { TCU_SIG_STEERING_STATUS_ACTUAL_ANGLE, 0u },   /* 146: Steering_Status_ActualAngle */
    { TCU_SIG_STEERING_STATUS_COMMANDED_ANGLE, 0u },   /* 147: Steering_Status_CommandedAngle */
    { TCU_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 148: Steering_Status_E2E_AliveCounter */
    { TCU_SIG_STEERING_STATUS_E_2_E_CRC_8, 0u },   /* 149: Steering_Status_E2E_CRC8 */
    { TCU_SIG_STEERING_STATUS_E_2_E_DATA_ID, 0u },   /* 150: Steering_Status_E2E_DataID */
    { TCU_SIG_STEERING_STATUS_SERVO_CURRENT_M_A, 0u },   /* 151: Steering_Status_ServoCurrent_mA */
    { TCU_SIG_STEERING_STATUS_STEER_FAULT_STATUS, 0u },   /* 152: Steering_Status_SteerFaultStatus */
    { TCU_SIG_STEERING_STATUS_STEER_MODE, 0u },   /* 153: Steering_Status_SteerMode */
    { TCU_SIG_TCU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 154: TCU_Heartbeat_AliveCounter */
    { TCU_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 155: TCU_Heartbeat_E2E_AliveCounter */
    { TCU_SIG_TCU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 156: TCU_Heartbeat_E2E_CRC8 */
    { TCU_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 157: TCU_Heartbeat_E2E_DataID */
    { TCU_SIG_TCU_HEARTBEAT_ECU_ID, 0u },   /* 158: TCU_Heartbeat_ECU_ID */
    { TCU_SIG_TORQUE_REQUEST_DIRECTION, 0u },   /* 159: Torque_Request_Direction */
    { TCU_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER, 0u },   /* 160: Torque_Request_E2E_AliveCounter */
    { TCU_SIG_TORQUE_REQUEST_E_2_E_CRC_8, 0u },   /* 161: Torque_Request_E2E_CRC8 */
    { TCU_SIG_TORQUE_REQUEST_E_2_E_DATA_ID, 0u },   /* 162: Torque_Request_E2E_DataID */
    { TCU_SIG_TORQUE_REQUEST_PEDAL_FAULT, 0u },   /* 163: Torque_Request_PedalFault */
    { TCU_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, 0u },   /* 164: Torque_Request_PedalPosition1 */
    { TCU_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, 0u },   /* 165: Torque_Request_PedalPosition2 */
    { TCU_SIG_TORQUE_REQUEST_TORQUE_REQUEST, 0u },   /* 166: Torque_Request_TorqueRequest */
    { TCU_SIG_UDS_FUNC_REQUEST_UDS_DATA, 0u },   /* 167: UDS_Func_Request_UDS_Data */
    { TCU_SIG_UDS_PHYS_REQ_CVC_UDS_DATA, 0u },   /* 168: UDS_Phys_Req_CVC_UDS_Data */
    { TCU_SIG_UDS_PHYS_REQ_FZC_UDS_DATA, 0u },   /* 169: UDS_Phys_Req_FZC_UDS_Data */
    { TCU_SIG_UDS_PHYS_REQ_RZC_UDS_DATA, 0u },   /* 170: UDS_Phys_Req_RZC_UDS_Data */
    { TCU_SIG_UDS_PHYS_REQ_TCU_UDS_DATA, 0u },   /* 171: UDS_Phys_Req_TCU_UDS_Data */
    { TCU_SIG_UDS_RESP_CVC_UDS_DATA, 0u },   /* 172: UDS_Resp_CVC_UDS_Data */
    { TCU_SIG_UDS_RESP_FZC_UDS_DATA, 0u },   /* 173: UDS_Resp_FZC_UDS_Data */
    { TCU_SIG_UDS_RESP_RZC_UDS_DATA, 0u },   /* 174: UDS_Resp_RZC_UDS_Data */
    { TCU_SIG_UDS_RESP_TCU_UDS_DATA, 0u },   /* 175: UDS_Resp_TCU_UDS_Data */
    { TCU_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, 0u },   /* 176: Vehicle_State_E2E_AliveCounter */
    { TCU_SIG_VEHICLE_STATE_E_2_E_CRC_8, 0u },   /* 177: Vehicle_State_E2E_CRC8 */
    { TCU_SIG_VEHICLE_STATE_E_2_E_DATA_ID, 0u },   /* 178: Vehicle_State_E2E_DataID */
    { TCU_SIG_VEHICLE_STATE_FAULT_MASK, 0u },   /* 179: Vehicle_State_FaultMask */
    { TCU_SIG_VEHICLE_STATE_SPEED_LIMIT, 0u },   /* 180: Vehicle_State_SpeedLimit */
    { TCU_SIG_VEHICLE_STATE_TORQUE_LIMIT, 0u },   /* 181: Vehicle_State_TorqueLimit */
    { TCU_SIG_VEHICLE_STATE_VEHICLE_STATE, 0u },   /* 182: Vehicle_State_VehicleState */
};

/* ==================================================================
 * Runnable Configuration Table
 * Priority: higher number = executes first within same period
 * ================================================================== */

static const Rte_RunnableConfigType tcu_runnable_config[] = {
    /* func,                        periodMs, priority, seId */
};

#define TCU_RUNNABLE_COUNT  (sizeof(tcu_runnable_config) / sizeof(tcu_runnable_config[0]))

/* ==================================================================
 * Aggregate RTE Configuration
 * ================================================================== */

const Rte_ConfigType tcu_rte_config = {
    .signalConfig   = tcu_signal_config,
    .signalCount    = TCU_SIG_COUNT,
    .runnableConfig = tcu_runnable_config,
    .runnableCount  = (uint8)TCU_RUNNABLE_COUNT,
};
