/**
 * @file    CanIf_Cfg_Rzc.c
 * @brief   CanIf configuration for RZC — CAN ID to PDU routing
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "CanIf.h"
#include "Rzc_Cfg.h"

/* ==================================================================
 * TX PDU Configuration Table
 * Maps CAN TX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_TxPduConfigType rzc_tx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc, hth */
    { 0x012u,  RZC_COM_TX_RZC_HEARTBEAT,  4u, 0u },
    { 0x300u,  RZC_COM_TX_MOTOR_STATUS,  8u, 0u },
    { 0x301u,  RZC_COM_TX_MOTOR_CURRENT,  8u, 0u },
    { 0x302u,  RZC_COM_TX_MOTOR_TEMPERATURE,  8u, 0u },
    { 0x303u,  RZC_COM_TX_BATTERY_STATUS,  6u, 0u },
    { 0x500u,  RZC_COM_TX_DTC_BROADCAST,  8u, 0u },
    { 0x555u,  RZC_COM_TX_XCP_RESP_RZC,  8u, 0u },
    { 0x7EAu,  RZC_COM_TX_UDS_RESP_RZC,  8u, 0u },
};

#define RZC_CANIF_TX_PDU_COUNT  (sizeof(rzc_tx_pdu_config) / sizeof(rzc_tx_pdu_config[0]))

/* ==================================================================
 * RX PDU Configuration Table
 * Maps CAN RX ID → upper-layer (Com) PDU ID
 * ================================================================== */

static const CanIf_RxPduConfigType rzc_rx_pdu_config[] = {
    /* canId,       upperPduId,                                      dlc, isExtended */
    { 0x001u,  RZC_COM_RX_ESTOP_BROADCAST,  4u, FALSE },
    { 0x010u,  RZC_COM_RX_CVC_HEARTBEAT,  4u, FALSE },
    { 0x011u,  RZC_COM_RX_FZC_HEARTBEAT,  4u, FALSE },
    { 0x013u,  RZC_COM_RX_SC_STATUS,  4u, FALSE },
    { 0x014u,  RZC_COM_RX_ICU_HEARTBEAT,  4u, FALSE },
    { 0x015u,  RZC_COM_RX_TCU_HEARTBEAT,  4u, FALSE },
    { 0x016u,  RZC_COM_RX_BCM_HEARTBEAT,  4u, FALSE },
    { 0x100u,  RZC_COM_RX_VEHICLE_STATE,  6u, FALSE },
    { 0x101u,  RZC_COM_RX_TORQUE_REQUEST,  8u, FALSE },
    { 0x102u,  RZC_COM_RX_STEER_COMMAND,  8u, FALSE },
    { 0x103u,  RZC_COM_RX_BRAKE_COMMAND,  8u, FALSE },
    { 0x200u,  RZC_COM_RX_STEERING_STATUS,  8u, FALSE },
    { 0x201u,  RZC_COM_RX_BRAKE_STATUS,  8u, FALSE },
    { 0x210u,  RZC_COM_RX_BRAKE_FAULT,  4u, FALSE },
    { 0x211u,  RZC_COM_RX_MOTOR_CUTOFF_REQ,  4u, FALSE },
    { 0x220u,  RZC_COM_RX_LIDAR_DISTANCE,  8u, FALSE },
    { 0x350u,  RZC_COM_RX_BODY_CONTROL_CMD,  4u, FALSE },
    { 0x400u,  RZC_COM_RX_LIGHT_STATUS,  4u, FALSE },
    { 0x401u,  RZC_COM_RX_INDICATOR_STATE,  4u, FALSE },
    { 0x402u,  RZC_COM_RX_DOOR_LOCK_STATUS,  2u, FALSE },
    { 0x500u,  RZC_COM_RX_DTC_BROADCAST,  8u, FALSE },
    { 0x550u,  RZC_COM_RX_XCP_REQ_CVC,  8u, FALSE },
    { 0x551u,  RZC_COM_RX_XCP_RESP_CVC,  8u, FALSE },
    { 0x552u,  RZC_COM_RX_XCP_REQ_FZC,  8u, FALSE },
    { 0x553u,  RZC_COM_RX_XCP_RESP_FZC,  8u, FALSE },
    { 0x554u,  RZC_COM_RX_XCP_REQ_RZC,  8u, FALSE },
    { 0x556u,  RZC_COM_RX_XCP_REQ_SC,  8u, FALSE },
    { 0x557u,  RZC_COM_RX_XCP_RESP_SC,  8u, FALSE },
    { 0x600u,  RZC_COM_RX_FZC_VIRTUAL_SENSORS,  8u, FALSE },
    { 0x601u,  RZC_COM_RX_RZC_VIRTUAL_SENSORS,  8u, FALSE },
    { 0x644u,  RZC_COM_RX_UDS_RESP_TCU,  8u, FALSE },
    { 0x7DFu,  RZC_COM_RX_UDS_FUNC_REQUEST,  8u, FALSE },
    { 0x7E0u,  RZC_COM_RX_UDS_PHYS_REQ_CVC,  8u, FALSE },
    { 0x7E1u,  RZC_COM_RX_UDS_PHYS_REQ_FZC,  8u, FALSE },
    { 0x7E2u,  RZC_COM_RX_UDS_PHYS_REQ_RZC,  8u, FALSE },
    { 0x7E3u,  RZC_COM_RX_UDS_PHYS_REQ_TCU,  8u, FALSE },
    { 0x7E8u,  RZC_COM_RX_UDS_RESP_CVC,  8u, FALSE },
    { 0x7E9u,  RZC_COM_RX_UDS_RESP_FZC,  8u, FALSE },
};

#define RZC_CANIF_RX_PDU_COUNT  (sizeof(rzc_rx_pdu_config) / sizeof(rzc_rx_pdu_config[0]))

/* ==================================================================
 * Aggregate CanIf Configuration
 * ================================================================== */

const CanIf_ConfigType rzc_canif_config = {
    .txPduConfig = rzc_tx_pdu_config,
    .txPduCount  = (uint8)RZC_CANIF_TX_PDU_COUNT,
    .rxPduConfig = rzc_rx_pdu_config,
    .rxPduCount  = (uint8)RZC_CANIF_RX_PDU_COUNT,
    .e2eRxCheck  = NULL_PTR,
};
