/**
 * @file    PduR_Cfg_Rzc.c
 * @brief   PduR configuration for RZC — CanIf ↔ Com routing
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "PduR.h"
#include "Rzc_Cfg.h"

/* ==================================================================
 * RX Routing Table — CanIf RX PDU → Com RX PDU
 * ================================================================== */

static const PduR_RoutingTableType rzc_pdur_routing[] = {
    /* RxPduId (CanIf),                            Destination,       UpperPduId (Com) */
    { RZC_COM_RX_ESTOP_BROADCAST,  PDUR_DEST_COM,  RZC_COM_RX_ESTOP_BROADCAST },   /* 0x001 EStop_Broadcast */
    { RZC_COM_RX_CVC_HEARTBEAT,  PDUR_DEST_COM,  RZC_COM_RX_CVC_HEARTBEAT },   /* 0x010 CVC_Heartbeat */
    { RZC_COM_RX_FZC_HEARTBEAT,  PDUR_DEST_COM,  RZC_COM_RX_FZC_HEARTBEAT },   /* 0x011 FZC_Heartbeat */
    { RZC_COM_RX_SC_STATUS,  PDUR_DEST_COM,  RZC_COM_RX_SC_STATUS },   /* 0x013 SC_Status */
    { RZC_COM_RX_ICU_HEARTBEAT,  PDUR_DEST_COM,  RZC_COM_RX_ICU_HEARTBEAT },   /* 0x014 ICU_Heartbeat */
    { RZC_COM_RX_TCU_HEARTBEAT,  PDUR_DEST_COM,  RZC_COM_RX_TCU_HEARTBEAT },   /* 0x015 TCU_Heartbeat */
    { RZC_COM_RX_BCM_HEARTBEAT,  PDUR_DEST_COM,  RZC_COM_RX_BCM_HEARTBEAT },   /* 0x016 BCM_Heartbeat */
    { RZC_COM_RX_VEHICLE_STATE,  PDUR_DEST_COM,  RZC_COM_RX_VEHICLE_STATE },   /* 0x100 Vehicle_State */
    { RZC_COM_RX_TORQUE_REQUEST,  PDUR_DEST_COM,  RZC_COM_RX_TORQUE_REQUEST },   /* 0x101 Torque_Request */
    { RZC_COM_RX_STEER_COMMAND,  PDUR_DEST_COM,  RZC_COM_RX_STEER_COMMAND },   /* 0x102 Steer_Command */
    { RZC_COM_RX_BRAKE_COMMAND,  PDUR_DEST_COM,  RZC_COM_RX_BRAKE_COMMAND },   /* 0x103 Brake_Command */
    { RZC_COM_RX_STEERING_STATUS,  PDUR_DEST_COM,  RZC_COM_RX_STEERING_STATUS },   /* 0x200 Steering_Status */
    { RZC_COM_RX_BRAKE_STATUS,  PDUR_DEST_COM,  RZC_COM_RX_BRAKE_STATUS },   /* 0x201 Brake_Status */
    { RZC_COM_RX_BRAKE_FAULT,  PDUR_DEST_COM,  RZC_COM_RX_BRAKE_FAULT },   /* 0x210 Brake_Fault */
    { RZC_COM_RX_MOTOR_CUTOFF_REQ,  PDUR_DEST_COM,  RZC_COM_RX_MOTOR_CUTOFF_REQ },   /* 0x211 Motor_Cutoff_Req */
    { RZC_COM_RX_LIDAR_DISTANCE,  PDUR_DEST_COM,  RZC_COM_RX_LIDAR_DISTANCE },   /* 0x220 Lidar_Distance */
    { RZC_COM_RX_BODY_CONTROL_CMD,  PDUR_DEST_COM,  RZC_COM_RX_BODY_CONTROL_CMD },   /* 0x350 Body_Control_Cmd */
    { RZC_COM_RX_LIGHT_STATUS,  PDUR_DEST_COM,  RZC_COM_RX_LIGHT_STATUS },   /* 0x400 Light_Status */
    { RZC_COM_RX_INDICATOR_STATE,  PDUR_DEST_COM,  RZC_COM_RX_INDICATOR_STATE },   /* 0x401 Indicator_State */
    { RZC_COM_RX_DOOR_LOCK_STATUS,  PDUR_DEST_COM,  RZC_COM_RX_DOOR_LOCK_STATUS },   /* 0x402 Door_Lock_Status */
    { RZC_COM_RX_DTC_BROADCAST,  PDUR_DEST_COM,  RZC_COM_RX_DTC_BROADCAST },   /* 0x500 DTC_Broadcast */
    { RZC_COM_RX_FZC_VIRTUAL_SENSORS,  PDUR_DEST_COM,  RZC_COM_RX_FZC_VIRTUAL_SENSORS },   /* 0x600 FZC_Virtual_Sensors */
    { RZC_COM_RX_RZC_VIRTUAL_SENSORS,  PDUR_DEST_COM,  RZC_COM_RX_RZC_VIRTUAL_SENSORS },   /* 0x601 RZC_Virtual_Sensors */
    { RZC_COM_RX_UDS_RESP_TCU,  PDUR_DEST_COM,  RZC_COM_RX_UDS_RESP_TCU },   /* 0x644 UDS_Resp_TCU */
    { RZC_COM_RX_UDS_FUNC_REQUEST,  PDUR_DEST_COM,  RZC_COM_RX_UDS_FUNC_REQUEST },   /* 0x7DF UDS_Func_Request */
    { RZC_COM_RX_UDS_PHYS_REQ_CVC,  PDUR_DEST_COM,  RZC_COM_RX_UDS_PHYS_REQ_CVC },   /* 0x7E0 UDS_Phys_Req_CVC */
    { RZC_COM_RX_UDS_PHYS_REQ_FZC,  PDUR_DEST_COM,  RZC_COM_RX_UDS_PHYS_REQ_FZC },   /* 0x7E1 UDS_Phys_Req_FZC */
    { RZC_COM_RX_UDS_PHYS_REQ_RZC,  PDUR_DEST_COM,  RZC_COM_RX_UDS_PHYS_REQ_RZC },   /* 0x7E2 UDS_Phys_Req_RZC */
    { RZC_COM_RX_UDS_PHYS_REQ_TCU,  PDUR_DEST_COM,  RZC_COM_RX_UDS_PHYS_REQ_TCU },   /* 0x7E3 UDS_Phys_Req_TCU */
    { RZC_COM_RX_UDS_RESP_CVC,  PDUR_DEST_COM,  RZC_COM_RX_UDS_RESP_CVC },   /* 0x7E8 UDS_Resp_CVC */
    { RZC_COM_RX_UDS_RESP_FZC,  PDUR_DEST_COM,  RZC_COM_RX_UDS_RESP_FZC },   /* 0x7E9 UDS_Resp_FZC */
};

/* ==================================================================
 * Aggregate PduR Configuration
 * ================================================================== */

const PduR_ConfigType rzc_pdur_config = {
    .routingTable = rzc_pdur_routing,
    .routingCount = (uint8)(sizeof(rzc_pdur_routing) / sizeof(rzc_pdur_routing[0])),
};
