/**
 * @file    Rte_Cfg_Rzc.c
 * @brief   RTE configuration for RZC — signal table and runnable table
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Rte.h"
#include "Rzc_Cfg.h"

/* ==================================================================
 * Forward declarations for SWC runnables
 * ================================================================== */

extern void Swc_Battery_MainFunction(void);
extern void Swc_Battery_Init(void);
extern void Swc_CurrentMonitor_MainFunction(void);
extern void Swc_CurrentMonitor_Init(void);
extern void Swc_Encoder_MainFunction(void);
extern void Swc_Encoder_Init(void);
extern void Swc_Heartbeat_MainFunction(void);
extern void Swc_Motor_MainFunction(void);
extern void Swc_Motor_Init(void);
extern void Swc_RzcCom_Receive(void);
extern void Swc_RzcCom_TransmitSchedule(void);
extern void Swc_RzcCom_Init(void);
extern void Swc_RzcDcm_Init(void);
extern void Swc_RzcNvm_Init(void);
extern void Swc_RzcSafety_MainFunction(void);
extern void Swc_RzcSafety_Init(void);
extern void Swc_RzcScheduler_Init(void);
extern void Swc_RzcSelfTest_Init(void);
extern void Swc_RzcSensorFeeder_MainFunction(void);
extern void Swc_RzcSensorFeeder_Init(void);
extern void Swc_TempMonitor_MainFunction(void);
extern void Swc_TempMonitor_Init(void);

/* ==================================================================
 * Signal Configuration Table
 * ================================================================== */

static const Rte_SignalConfigType rzc_signal_config[RZC_SIG_COUNT] = {
    /* BSW well-known signals (0-15) — initial values */
    {  0u, 0u },   /* RTE_SIG_TORQUE_REQUEST */
    {  1u, 0u },   /* RTE_SIG_STEERING_ANGLE */
    {  2u, 0u },   /* RTE_SIG_VEHICLE_SPEED */
    {  3u, 0u },   /* RTE_SIG_BRAKE_PRESSURE */
    {  4u, 0u },   /* RTE_SIG_MOTOR_STATUS */
    {  5u, 0u },   /* RTE_SIG_BATTERY_VOLTAGE */
    {  6u, 0u },   /* RTE_SIG_BATTERY_CURRENT */
    {  7u, 0u },   /* RTE_SIG_MOTOR_TEMP */
    {  8u, 0u },   /* RTE_SIG_ESTOP_STATUS */
    {  9u, 0u },   /* RTE_SIG_HEARTBEAT */
    { 10u, 0u },   /* Reserved                */
    { 11u, 0u },   /* Reserved                */
    { 12u, 0u },   /* Reserved                */
    { 13u, 0u },   /* Reserved                */
    { 14u, 0u },   /* Reserved                */
    { 15u, 0u },   /* Reserved                */

    /* RZC application signals (16+) */
    { RZC_SIG_BATTERY_STATUS_BATTERY_STATUS, 0u },   /* 16: Battery_Status_BatteryStatus */
    { RZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V, 0u },   /* 17: Battery_Status_BatteryVoltage_mV */
    { RZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 18: Battery_Status_E2E_AliveCounter */
    { RZC_SIG_BATTERY_STATUS_E_2_E_CRC_8, 0u },   /* 19: Battery_Status_E2E_CRC8 */
    { RZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID, 0u },   /* 20: Battery_Status_E2E_DataID */
    { RZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD, 0u },   /* 21: Body_Control_Cmd_DoorLockCmd */
    { RZC_SIG_BODY_CONTROL_CMD_HAZARD_CMD, 0u },   /* 22: Body_Control_Cmd_HazardCmd */
    { RZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD, 0u },   /* 23: Body_Control_Cmd_HeadlightCmd */
    { RZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD, 0u },   /* 24: Body_Control_Cmd_TailLightCmd */
    { RZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD, 0u },   /* 25: Body_Control_Cmd_TurnSignalCmd */
    { RZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD, 0u },   /* 26: Brake_Command_BrakeForceCmd */
    { RZC_SIG_BRAKE_COMMAND_BRAKE_MODE, 0u },   /* 27: Brake_Command_BrakeMode */
    { RZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 28: Brake_Command_E2E_AliveCounter */
    { RZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8, 0u },   /* 29: Brake_Command_E2E_CRC8 */
    { RZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID, 0u },   /* 30: Brake_Command_E2E_DataID */
    { RZC_SIG_BRAKE_COMMAND_VEHICLE_STATE, 0u },   /* 31: Brake_Command_VehicleState */
    { RZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE, 0u },   /* 32: Brake_Fault_CommandedBrake */
    { RZC_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER, 0u },   /* 33: Brake_Fault_E2E_AliveCounter */
    { RZC_SIG_BRAKE_FAULT_E_2_E_CRC_8, 0u },   /* 34: Brake_Fault_E2E_CRC8 */
    { RZC_SIG_BRAKE_FAULT_E_2_E_DATA_ID, 0u },   /* 35: Brake_Fault_E2E_DataID */
    { RZC_SIG_BRAKE_FAULT_FAULT_TYPE, 0u },   /* 36: Brake_Fault_FaultType */
    { RZC_SIG_BRAKE_FAULT_MEASURED_BRAKE, 0u },   /* 37: Brake_Fault_MeasuredBrake */
    { RZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO, 0u },   /* 38: Brake_Status_BrakeCommandEcho */
    { RZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS, 0u },   /* 39: Brake_Status_BrakeFaultStatus */
    { RZC_SIG_BRAKE_STATUS_BRAKE_MODE, 0u },   /* 40: Brake_Status_BrakeMode */
    { RZC_SIG_BRAKE_STATUS_BRAKE_POSITION, 0u },   /* 41: Brake_Status_BrakePosition */
    { RZC_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 42: Brake_Status_E2E_AliveCounter */
    { RZC_SIG_BRAKE_STATUS_E_2_E_CRC_8, 0u },   /* 43: Brake_Status_E2E_CRC8 */
    { RZC_SIG_BRAKE_STATUS_E_2_E_DATA_ID, 0u },   /* 44: Brake_Status_E2E_DataID */
    { RZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A, 0u },   /* 45: Brake_Status_ServoCurrent_mA */
    { RZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 46: CVC_Heartbeat_E2E_AliveCounter */
    { RZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 47: CVC_Heartbeat_E2E_CRC8 */
    { RZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 48: CVC_Heartbeat_E2E_DataID */
    { RZC_SIG_CVC_HEARTBEAT_ECU_ID, 0u },   /* 49: CVC_Heartbeat_ECU_ID */
    { RZC_SIG_CVC_HEARTBEAT_FAULT_STATUS, 0u },   /* 50: CVC_Heartbeat_FaultStatus */
    { RZC_SIG_CVC_HEARTBEAT_OPERATING_MODE, 0u },   /* 51: CVC_Heartbeat_OperatingMode */
    { RZC_SIG_DTC_BROADCAST_DTC_NUMBER, 0u },   /* 52: DTC_Broadcast_DTC_Number */
    { RZC_SIG_DTC_BROADCAST_DTC_STATUS, 0u },   /* 53: DTC_Broadcast_DTC_Status */
    { RZC_SIG_DTC_BROADCAST_ECU_SOURCE, 0u },   /* 54: DTC_Broadcast_ECU_Source */
    { RZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0, 0u },   /* 55: DTC_Broadcast_FreezeFrame0 */
    { RZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1, 0u },   /* 56: DTC_Broadcast_FreezeFrame1 */
    { RZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT, 0u },   /* 57: DTC_Broadcast_OccurrenceCount */
    { RZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK, 0u },   /* 58: Door_Lock_Status_CentralLock */
    { RZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK, 0u },   /* 59: Door_Lock_Status_FrontLeftLock */
    { RZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK, 0u },   /* 60: Door_Lock_Status_FrontRightLock */
    { RZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK, 0u },   /* 61: Door_Lock_Status_RearLeftLock */
    { RZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK, 0u },   /* 62: Door_Lock_Status_RearRightLock */
    { RZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER, 0u },   /* 63: EStop_Broadcast_E2E_AliveCounter */
    { RZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8, 0u },   /* 64: EStop_Broadcast_E2E_CRC8 */
    { RZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID, 0u },   /* 65: EStop_Broadcast_E2E_DataID */
    { RZC_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE, 0u },   /* 66: EStop_Broadcast_EStop_Active */
    { RZC_SIG_ESTOP_BROADCAST_ESTOP_SOURCE, 0u },   /* 67: EStop_Broadcast_EStop_Source */
    { RZC_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 68: FZC_Heartbeat_E2E_AliveCounter */
    { RZC_SIG_FZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 69: FZC_Heartbeat_E2E_CRC8 */
    { RZC_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 70: FZC_Heartbeat_E2E_DataID */
    { RZC_SIG_FZC_HEARTBEAT_ECU_ID, 0u },   /* 71: FZC_Heartbeat_ECU_ID */
    { RZC_SIG_FZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 72: FZC_Heartbeat_FaultStatus */
    { RZC_SIG_FZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 73: FZC_Heartbeat_OperatingMode */
    { RZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 74: ICU_Heartbeat_AliveCounter */
    { RZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 75: ICU_Heartbeat_E2E_AliveCounter */
    { RZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 76: ICU_Heartbeat_E2E_CRC8 */
    { RZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 77: ICU_Heartbeat_E2E_DataID */
    { RZC_SIG_ICU_HEARTBEAT_ECU_ID, 0u },   /* 78: ICU_Heartbeat_ECU_ID */
    { RZC_SIG_INDICATOR_STATE_BLINK_STATE, 0u },   /* 79: Indicator_State_BlinkState */
    { RZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE, 0u },   /* 80: Indicator_State_HazardActive */
    { RZC_SIG_INDICATOR_STATE_LEFT_INDICATOR, 0u },   /* 81: Indicator_State_LeftIndicator */
    { RZC_SIG_INDICATOR_STATE_RIGHT_INDICATOR, 0u },   /* 82: Indicator_State_RightIndicator */
    { RZC_SIG_LIDAR_DISTANCE_DISTANCE_CM, 0u },   /* 83: Lidar_Distance_Distance_cm */
    { RZC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER, 0u },   /* 84: Lidar_Distance_E2E_AliveCounter */
    { RZC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8, 0u },   /* 85: Lidar_Distance_E2E_CRC8 */
    { RZC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID, 0u },   /* 86: Lidar_Distance_E2E_DataID */
    { RZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE, 0u },   /* 87: Lidar_Distance_ObstacleZone */
    { RZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS, 0u },   /* 88: Lidar_Distance_SensorStatus */
    { RZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH, 0u },   /* 89: Lidar_Distance_SignalStrength */
    { RZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON, 0u },   /* 90: Light_Status_BrakeLightOn */
    { RZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON, 0u },   /* 91: Light_Status_FogLightOn */
    { RZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL, 0u },   /* 92: Light_Status_HeadlightLevel */
    { RZC_SIG_LIGHT_STATUS_HEADLIGHT_ON, 0u },   /* 93: Light_Status_HeadlightOn */
    { RZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON, 0u },   /* 94: Light_Status_TailLightOn */
    { RZC_SIG_MOTOR_CURRENT_CURRENT_DIRECTION, 0u },   /* 95: Motor_Current_CurrentDirection */
    { RZC_SIG_MOTOR_CURRENT_CURRENT_M_A, 0u },   /* 96: Motor_Current_Current_mA */
    { RZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER, 0u },   /* 97: Motor_Current_E2E_AliveCounter */
    { RZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8, 0u },   /* 98: Motor_Current_E2E_CRC8 */
    { RZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID, 0u },   /* 99: Motor_Current_E2E_DataID */
    { RZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE, 0u },   /* 100: Motor_Current_MotorEnable */
    { RZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG, 0u },   /* 101: Motor_Current_OvercurrentFlag */
    { RZC_SIG_MOTOR_CURRENT_TORQUE_ECHO, 0u },   /* 102: Motor_Current_TorqueEcho */
    { RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER, 0u },   /* 103: Motor_Cutoff_Req_E2E_AliveCounter */
    { RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8, 0u },   /* 104: Motor_Cutoff_Req_E2E_CRC8 */
    { RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID, 0u },   /* 105: Motor_Cutoff_Req_E2E_DataID */
    { RZC_SIG_MOTOR_CUTOFF_REQ_REASON, 0u },   /* 106: Motor_Cutoff_Req_Reason */
    { RZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE, 0u },   /* 107: Motor_Cutoff_Req_RequestType */
    { RZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 108: Motor_Status_E2E_AliveCounter */
    { RZC_SIG_MOTOR_STATUS_E_2_E_CRC_8, 0u },   /* 109: Motor_Status_E2E_CRC8 */
    { RZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID, 0u },   /* 110: Motor_Status_E2E_DataID */
    { RZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION, 0u },   /* 111: Motor_Status_MotorDirection */
    { RZC_SIG_MOTOR_STATUS_MOTOR_ENABLE, 0u },   /* 112: Motor_Status_MotorEnable */
    { RZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS, 0u },   /* 113: Motor_Status_MotorFaultStatus */
    { RZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM, 0u },   /* 114: Motor_Status_MotorSpeed_RPM */
    { RZC_SIG_MOTOR_STATUS_TORQUE_ECHO, 0u },   /* 115: Motor_Status_TorqueEcho */
    { RZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT, 0u },   /* 116: Motor_Temperature_DeratingPercent */
    { RZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER, 0u },   /* 117: Motor_Temperature_E2E_AliveCounter */
    { RZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8, 0u },   /* 118: Motor_Temperature_E2E_CRC8 */
    { RZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID, 0u },   /* 119: Motor_Temperature_E2E_DataID */
    { RZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C, 0u },   /* 120: Motor_Temperature_WindingTemp1_C */
    { RZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C, 0u },   /* 121: Motor_Temperature_WindingTemp2_C */
    { RZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 122: RZC_Heartbeat_E2E_AliveCounter */
    { RZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 123: RZC_Heartbeat_E2E_CRC8 */
    { RZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 124: RZC_Heartbeat_E2E_DataID */
    { RZC_SIG_RZC_HEARTBEAT_ECU_ID, 0u },   /* 125: RZC_Heartbeat_ECU_ID */
    { RZC_SIG_RZC_HEARTBEAT_FAULT_STATUS, 0u },   /* 126: RZC_Heartbeat_FaultStatus */
    { RZC_SIG_RZC_HEARTBEAT_OPERATING_MODE, 0u },   /* 127: RZC_Heartbeat_OperatingMode */
    { RZC_SIG_SC_STATUS_ECU_HEALTH, 0u },   /* 128: SC_Status_ECU_Health */
    { RZC_SIG_SC_STATUS_FAULT_REASON, 0u },   /* 129: SC_Status_FaultReason */
    { RZC_SIG_SC_STATUS_RELAY_STATE, 0u },   /* 130: SC_Status_RelayState */
    { RZC_SIG_SC_STATUS_SC_ALIVE_COUNTER, 0u },   /* 131: SC_Status_SC_AliveCounter */
    { RZC_SIG_SC_STATUS_SC_CRC_8, 0u },   /* 132: SC_Status_SC_CRC8 */
    { RZC_SIG_SC_STATUS_SC_FAULT_FLAGS, 0u },   /* 133: SC_Status_SC_FaultFlags */
    { RZC_SIG_SC_STATUS_SC_MODE, 0u },   /* 134: SC_Status_SC_Mode */
    { RZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER, 0u },   /* 135: Steer_Command_E2E_AliveCounter */
    { RZC_SIG_STEER_COMMAND_E_2_E_CRC_8, 0u },   /* 136: Steer_Command_E2E_CRC8 */
    { RZC_SIG_STEER_COMMAND_E_2_E_DATA_ID, 0u },   /* 137: Steer_Command_E2E_DataID */
    { RZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD, 0u },   /* 138: Steer_Command_SteerAngleCmd */
    { RZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT, 0u },   /* 139: Steer_Command_SteerRateLimit */
    { RZC_SIG_STEER_COMMAND_VEHICLE_STATE, 0u },   /* 140: Steer_Command_VehicleState */
    { RZC_SIG_STEERING_STATUS_ACTUAL_ANGLE, 0u },   /* 141: Steering_Status_ActualAngle */
    { RZC_SIG_STEERING_STATUS_COMMANDED_ANGLE, 0u },   /* 142: Steering_Status_CommandedAngle */
    { RZC_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER, 0u },   /* 143: Steering_Status_E2E_AliveCounter */
    { RZC_SIG_STEERING_STATUS_E_2_E_CRC_8, 0u },   /* 144: Steering_Status_E2E_CRC8 */
    { RZC_SIG_STEERING_STATUS_E_2_E_DATA_ID, 0u },   /* 145: Steering_Status_E2E_DataID */
    { RZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A, 0u },   /* 146: Steering_Status_ServoCurrent_mA */
    { RZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS, 0u },   /* 147: Steering_Status_SteerFaultStatus */
    { RZC_SIG_STEERING_STATUS_STEER_MODE, 0u },   /* 148: Steering_Status_SteerMode */
    { RZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER, 0u },   /* 149: TCU_Heartbeat_AliveCounter */
    { RZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER, 0u },   /* 150: TCU_Heartbeat_E2E_AliveCounter */
    { RZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8, 0u },   /* 151: TCU_Heartbeat_E2E_CRC8 */
    { RZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID, 0u },   /* 152: TCU_Heartbeat_E2E_DataID */
    { RZC_SIG_TCU_HEARTBEAT_ECU_ID, 0u },   /* 153: TCU_Heartbeat_ECU_ID */
    { RZC_SIG_TORQUE_REQUEST_DIRECTION, 0u },   /* 154: Torque_Request_Direction */
    { RZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER, 0u },   /* 155: Torque_Request_E2E_AliveCounter */
    { RZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8, 0u },   /* 156: Torque_Request_E2E_CRC8 */
    { RZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID, 0u },   /* 157: Torque_Request_E2E_DataID */
    { RZC_SIG_TORQUE_REQUEST_PEDAL_FAULT, 0u },   /* 158: Torque_Request_PedalFault */
    { RZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1, 0u },   /* 159: Torque_Request_PedalPosition1 */
    { RZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2, 0u },   /* 160: Torque_Request_PedalPosition2 */
    { RZC_SIG_TORQUE_REQUEST_TORQUE_REQUEST, 0u },   /* 161: Torque_Request_TorqueRequest */
    { RZC_SIG_UDS_FUNC_REQUEST_UDS_DATA, 0u },   /* 162: UDS_Func_Request_UDS_Data */
    { RZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA, 0u },   /* 163: UDS_Phys_Req_CVC_UDS_Data */
    { RZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA, 0u },   /* 164: UDS_Phys_Req_FZC_UDS_Data */
    { RZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA, 0u },   /* 165: UDS_Phys_Req_RZC_UDS_Data */
    { RZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA, 0u },   /* 166: UDS_Phys_Req_TCU_UDS_Data */
    { RZC_SIG_UDS_RESP_CVC_UDS_DATA, 0u },   /* 167: UDS_Resp_CVC_UDS_Data */
    { RZC_SIG_UDS_RESP_FZC_UDS_DATA, 0u },   /* 168: UDS_Resp_FZC_UDS_Data */
    { RZC_SIG_UDS_RESP_RZC_UDS_DATA, 0u },   /* 169: UDS_Resp_RZC_UDS_Data */
    { RZC_SIG_UDS_RESP_TCU_UDS_DATA, 0u },   /* 170: UDS_Resp_TCU_UDS_Data */
    { RZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER, 0u },   /* 171: Vehicle_State_E2E_AliveCounter */
    { RZC_SIG_VEHICLE_STATE_E_2_E_CRC_8, 0u },   /* 172: Vehicle_State_E2E_CRC8 */
    { RZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID, 0u },   /* 173: Vehicle_State_E2E_DataID */
    { RZC_SIG_VEHICLE_STATE_FAULT_MASK, 0u },   /* 174: Vehicle_State_FaultMask */
    { RZC_SIG_VEHICLE_STATE_SPEED_LIMIT, 0u },   /* 175: Vehicle_State_SpeedLimit */
    { RZC_SIG_VEHICLE_STATE_TORQUE_LIMIT, 0u },   /* 176: Vehicle_State_TorqueLimit */
    { RZC_SIG_VEHICLE_STATE_VEHICLE_STATE, 0u },   /* 177: Vehicle_State_VehicleState */
};

/* ==================================================================
 * Runnable Configuration Table
 * Priority: higher number = executes first within same period
 * ================================================================== */

static const Rte_RunnableConfigType rzc_runnable_config[] = {
    /* func,                        periodMs, priority, seId */
    { Swc_Battery_MainFunction,                  100u,     5u, 0xFFu },
    { Swc_Battery_Init,                            0u,     5u, 0xFFu },
    { Swc_CurrentMonitor_MainFunction,             1u,     5u, 0xFFu },
    { Swc_CurrentMonitor_Init,                     0u,     5u, 0xFFu },
    { Swc_Encoder_MainFunction,                   10u,     5u, 0xFFu },
    { Swc_Encoder_Init,                            0u,     5u, 0xFFu },
    { Swc_Heartbeat_MainFunction,                 50u,     5u, 0xFFu },
    { Swc_Motor_MainFunction,                     10u,     5u, 0xFFu },
    { Swc_Motor_Init,                              0u,     5u, 0xFFu },
    { Swc_RzcCom_Receive,                         10u,     5u, 0xFFu },
    { Swc_RzcCom_TransmitSchedule,                10u,     5u, 0xFFu },
    { Swc_RzcCom_Init,                             0u,     5u, 0xFFu },
    { Swc_RzcDcm_Init,                             0u,     5u, 0xFFu },
    { Swc_RzcNvm_Init,                             0u,     5u, 0xFFu },
    { Swc_RzcSafety_MainFunction,                100u,     5u, 0xFFu },
    { Swc_RzcSafety_Init,                          0u,     5u, 0xFFu },
    { Swc_RzcScheduler_Init,                       0u,     5u, 0xFFu },
    { Swc_RzcSelfTest_Init,                        0u,     5u, 0xFFu },
    { Swc_RzcSensorFeeder_MainFunction,           10u,     5u, 0xFFu },
    { Swc_RzcSensorFeeder_Init,                    0u,     5u, 0xFFu },
    { Swc_TempMonitor_MainFunction,              100u,     5u, 0xFFu },
    { Swc_TempMonitor_Init,                        0u,     5u, 0xFFu },
};

#define RZC_RUNNABLE_COUNT  (sizeof(rzc_runnable_config) / sizeof(rzc_runnable_config[0]))

/* ==================================================================
 * Aggregate RTE Configuration
 * ================================================================== */

const Rte_ConfigType rzc_rte_config = {
    .signalConfig   = rzc_signal_config,
    .signalCount    = RZC_SIG_COUNT,
    .runnableConfig = rzc_runnable_config,
    .runnableCount  = (uint8)RZC_RUNNABLE_COUNT,
};
