/**
 * @file    Rte_Swc_RzcDcm.h
 * @brief   Typed RTE wrappers for Swc_RzcDcm (RZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_RZCDCM_H
#define RTE_SWC_RZCDCM_H

#include "Rte.h"
#include "Rzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_RzcDcm
 *
 * Usage: #include "Rte_Swc_RzcDcm.h" in Swc_RzcDcm source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

#endif /* RTE_SWC_RZCDCM_H */
