/**
 * @file    Rte_Swc_Motor.h
 * @brief   Typed RTE wrappers for Swc_Motor (RZC)
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RTE_SWC_MOTOR_H
#define RTE_SWC_MOTOR_H

#include "Rte.h"
#include "Rzc_Cfg.h"

/* ====================================================================
 * Typed RTE Wrappers for Swc_Motor
 *
 * Usage: #include "Rte_Swc_Motor.h" in Swc_Motor source files.
 * Provides type-safe inline read/write instead of raw Rte_Read/Rte_Write.
 * ==================================================================== */

/**
 * @brief  Read TorqueRequest (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_TorqueRequest(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(RZC_SIG_TORQUE_REQUEST, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Read TorqueLimit (uint8)
 * @param  data  Pointer to receive the signal value
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Read_TorqueLimit(uint8 *data)
{
    uint32 tmp;
    Rte_StatusType status = Rte_Read(RZC_SIG_TORQUE_LIMIT, &tmp);
    if (status == RTE_E_OK)
    {
        *data = (uint8)tmp;
    }
    return status;
}

/**
 * @brief  Write MotorDirection (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MotorDirection(uint8 value)
{
    return Rte_Write(RZC_SIG_MOTOR_DIRECTION, (uint32)value);
}

/**
 * @brief  Write MotorEnable (boolean)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MotorEnable(boolean value)
{
    return Rte_Write(RZC_SIG_MOTOR_ENABLE, (uint32)value);
}

/**
 * @brief  Write MotorSpeed_RPM (uint16)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MotorSpeed_RPM(uint16 value)
{
    return Rte_Write(RZC_SIG_MOTOR_SPEED_RPM, (uint32)value);
}

/**
 * @brief  Write MotorFaultStatus (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_MotorFaultStatus(uint8 value)
{
    return Rte_Write(RZC_SIG_MOTOR_FAULT_STATUS, (uint32)value);
}

/**
 * @brief  Write TorqueEcho (uint8)
 * @param  value  Signal value to transmit
 * @return Rte_StatusType (RTE_E_OK on success)
 */
static inline Rte_StatusType Rte_Write_TorqueEcho(uint8 value)
{
    return Rte_Write(RZC_SIG_TORQUE_ECHO, (uint32)value);
}

#endif /* RTE_SWC_MOTOR_H */
