/**
 * @file    Swc_CVC.c
 * @brief   SWC implementation for Swc_CVC (CVC)
 *
 * Generated by arxmlgen v1.0.0 — EDIT THIS FILE
 * This is a skeleton. Add your application logic here.
 * Source: TaktflowSystem.arxml
 */
#include "Swc_CVC.h"
#include "Rte_Swc_CVC.h"

/* ====================================================================
 * Runnable Implementations
 * ==================================================================== */

/**
 * @brief  Periodic runnable — 1ms cycle
 * @note   Priority: 9
 */
void Can_MainFunction_Read(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 8
 */
void Com_MainFunction_Rx(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 7
 */
void Swc_EStop_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 6
 */
void Swc_Pedal_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 5
 */
void Swc_VehicleState_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 4
 */
void Swc_Heartbeat_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 3
 */
void Swc_Dashboard_MainFunction(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 2
 */
void Com_MainFunction_Tx(void)
{
    /* TODO: Add periodic processing logic */
}

/**
 * @brief  Periodic runnable — 10ms cycle
 * @note   Priority: 1
 */
void Can_MainFunction_BusOff(void)
{
    /* TODO: Add periodic processing logic */
}

